* Flex Box

** Sources

| source                           | author       |
|----------------------------------+--------------|
| *CSS Flexible Box Layout Module* | W3C          |
| *CSS Flexbox Layout Guide*       | Chris Coyier |

** Terminology

- flex container :: Either a block, ~flex~, or inline-block, ~inline-flex~, element that creates
  a flex formatting context wherein its children become flex items. Floats cannot intrude. Margins
  will not collapse. Items are ordered independent of source.

- flex item :: Any direct child contained within a flex container. A flex formatting context dictates
  their size, order, and alignment.
  
- main axis :: The primary axis of a flex container along which flex items are laid out.
  Has the same orientation as the inline axis of the current writing mode.

- cross axis :: The axis perpendicular to the main axis.

- flex flow :: The main and cross axis directions of a flex container relative to writing mode.
  The cross axis always runs perpendicular to the main axis.

** Layout

#+begin_example
  # === Writing Mode: Left-to-Right ===
  
                 main size
                 --------------------------------------------------
                V                                                  V
              > +----------------◯---------------------------------+ <- cross start
             |  |                |                |                |
             |  |                |                |                | main axis
  cross size |  ◯------ 1 -------|------ 2 -------|------ 3 -------|---------->
             |  |                |                |                |
             |  | flex item      | flex item      | flex item      |
              > +--------------------------------------------------+ <- cross end
                ^ flex container |                                 ^
                |                | cross axis                      |
            main start           |                             main end
                                 V

  # === display ===

  +---------------+
  | +---+---+---+ |
  | | 1 | 2 | 3 | |
  | +---+---+---+ |
  +---------------+ flex
  | +---+---+---+ |
  | | 1 | 2 | 3 | |
  | +---+---+---+ |
  +---------------+

  +---------------+---------------+
  | +---+---+---+ | +---+---+---+ |
  | | 1 | 2 | 3 | | | 1 | 2 | 3 | | inline-flex
  | +---+---+---+ | +---+---+---+ |
  +---------------+---------------+
  
  # === flex-direction ===

  +---------------+
  | +---+---+---+ |
  | | 1 | 2 | 3 | | row
  | +---+---+---+ |
  +---------------+

  +---------------+
  | +---+---+---+ |
  | | 3 | 2 | 1 | | row-reverse
  | +---+---+---+ |
  +---------------+

  +-------+
  | +---+ |
  | | 1 | |
  | +---+ |
  | | 2 | |         column
  | +---+ |
  | | 3 | |
  | +---+ |
  +-------+

  +-------+
  | +---+ |
  | | 3 | |
  | +---+ |
  | | 2 | |         column-reverse
  | +---+ |
  | | 1 | |
  | +---+ |
  +-------+

  # === flex-wrap ===

  +---------------+
  | +---+---+---+ |
  | | 1 | 2 | 3 | | nowrap
  | +---+---+---+ |
  +---------------+

  +-----------+
  | +---+---+ |
  | | 1 | 2 | |
  | +---+---+ |     wrap
  | | 3 |     |
  | +---+     |
  +-----------+

  +-----------+
  | +---+     |
  | | 3 |     |
  | +---+---+ |     wrap-reverse
  | | 1 | 2 | |
  | +---+---+ |
  +-----------+

  # === justify-content ===
  
  +-----------------------------------+
  | +---+---+---+                     |
  | | 1 | 2 | 3 |                     | flex-start
  | +---+---+---+                     |
  +-----------------------------------+

  +-----------------------------------+
  |                     +---+---+---+ |
  |                     | 1 | 2 | 3 | | flex-end
  |                     +---+---+---+ |
  +-----------------------------------+

  +-----------------------------------+
  |           +---+---+---+           |
  |           | 1 | 2 | 3 |           | center
  |           +---+---+---+           |
  +-----------------------------------+

  +-----------------------------------+
  |+---+          +---+          +---+|
  || 1 |          | 2 |          | 3 || space-between
  |+---+          +---+          +---+|
  +-----------------------------------+

  +-----------|-----------|-----------+
  |   +---+   |   +---+   |   +---+   |
  |   | 1 |   |   | 2 |   |   | 3 |   | space-around
  |   +---+   |   +---+   |   +---+   |
  +-----------|-----------|-----------+

  +-----|---|-----|---|-----|---|-----+
  |     +---+     +---+     +---+     |
  |     | 1 |     | 2 |     | 3 |     | space-evenly
  |     +---+     +---+     +---+     |
  +-----|---|-----|---|-----|---|-----+

  # === align-items ===

  +---------------+
  | +---+---+---+ |
  | | 1 | 2 | 3 | |
  | +---|   |---+ | flex-start
  |     |   |     |
  |     +---+     |
  +---------------+

  +---------------+
  |     +---+     |
  |     | 2 |     |
  | +---|   |---+ | flex-end
  | | 1 |   | 3 | |
  | +---+---+---+ |
  +---------------+

  +---------------+
  |     +---+     |
  | +---| 2 |---+ |
  | | 1 |   | 3 | | center
  | +---|   |---+ |
  |     +---+     |
  +---------------+

  +---------------+
  | +---+---+---+ |
  | | 1 | 2 | 3 | |
  | |   |   |   | | stretch
  | |   |   |   | |
  | +---+---+---+ |
  +---------------+

  +---------------+
  | +---+---+---+ |
  | | 1 | 2 | 3 | |
 -------------------> baseline
  |     |   |     |
  |     +---+     |
  +---------------+

  # === align-content ===

  +-----------+
  | +---+---+ |
  | | 1 | 2 | |
  | +---+---+ |
  | | 3 |     |  flex-start
  | +---+     |
  |           |
  |           |
  +-----------+

  +-----------+
  |           |
  |           |
  | +---+---+ |
  | | 1 | 2 | |  flex-end
  | +---+---+ |
  | | 3 |     |
  | +---+     |
  +-----------+

  +-----------+
  |           |
  | +---+---+ |
  | | 1 | 2 | |
  | +---+---+ |  center
  | | 3 |     |
  | +---+     |
  |           |
  +-----------+

  +-----------+
  | +---+---+ |
  | | 1 | 2 | |
  | |   |   | |
  | +---+---+ |  stretch
  | | 3 |     |
  | |   |     |
  | +---+     |
  +-----------+

  +-----------+
  | +---+---+ |
  | | 1 | 2 | |
  | +---+---+ |
  |           |  space-between
  | +---+     |
  | | 3 |     |
  | +---+     |
  +-----------+

  +-----------+
  |           |
  | +---+---+ |
  | | 1 | 2 | |
  | +---+---+ |
  |           |
 --------------- space-around
  |           |
  | +---+     |
  | | 3 |     |
  | +---+     |
  |           |
  +-----------+

  # === gap: row column ===

  +---------------------+
  |+---+  +---+  +---+  |
  || 1 |  | 2 |  | 3 |  | gap: value
  |+---+  +---+  +---+  |
  +---------------------+

  +---------------------+
  |+---+  +---+  +---+  |
  || 1 |  | 2 |  | 3 |  |
  |+---+  +---+  +---+  |
  |                     | gap: value
  |+---+  +---+  +---+  |
  || 1 |  | 2 |  | 3 |  |
  |+---+  +---+  +---+  |
  +---------------------+

  +---------------------+
  |+---+   +---+   +---+|
  || 1 |   | 2 |   | 3 ||
  |+---+   +---+   +---+| gap: value (value * 2)
  |+---+   +---+   +---+|
  || 1 |   | 2 |   | 3 ||
  |+---+   +---+   +---+|
  +---------------------+
#+end_example

** Flex Property

- flex :: A shorthand property that sets how a flex item will grow or shrink
  to fit the space available in its container. Its constituent properties are
  ~flex-grow~, ~flex-shrink~, and ~flex-basis~.

- flex-grow :: Sets the flex grow factor, which specifies how much of the flex
  container's positive free space should be assigned to the targeted flex item's
  main size. A factor of 0 sets grow to false. A factor greater than zero grows
  the flex item relative to the grow factors of sibling flex items.

- flex-shrink :: Sets the flex shrink factor, which specifies how much of the flex
  container's negative free space should be assigned to the targeted flex item's
  main size. A factor of 0 sets shrink to false. A factor greater than zero shrinks
  the flex item relative to the shrink factors of sibling flex items.

- flex-basis :: Sets the initial main size of the targeted flex item.

| property        | grow | shrink | basis |
|-----------------+------+--------+-------|
| ~flex: initial~ |    0 |      1 | auto  |
| ~flex: none~    |    0 |      0 | auto  |
| ~flex: auto~    |    1 |      1 | auto  |
| ~flex: 2~       |    2 |      1 | 0%    |
| ~flex: 3rem~    |    1 |      1 | 3rem  |
| ~flex: 2 2~     |    2 |      2 | 0%    |
| ~flex: 1 1 50%~ |    1 |      1 | 50%   |
