* CSS Grid

** Sources

| source                  | author      |
|-------------------------+-------------|
| *Grid Cheat Sheet*      | Mari Simon  |
| *CSS Grid Layout Guide* | Chris House |

** Terminology

- grid container :: The element on which ~display: grid~ is applied.
  The direct parent of grid items.

- grid line :: The dividing lines, vertical and horizontal, that make
  up the structure of the grid.

- grid track :: The space between adjacent grid lines — the rows and columns.

- grid item :: The direct children of a grid container.

- grid cell :: The space between two adjacent row and column grid lines.
  A single unit within a grid container.

- grid area :: The space surrounded by four grid lines. A grid area may be
  composed of any number of grid cells.

#+begin_example
     row axis
    +-------------------+
    V                   V
    1   2   3   4   5   6
  1 +---+---+---+---+---+ <+
    |<- track --------->|  | +- cell
  2 +---+---+---+---+---+  | |
    |   | x | x | x |   |<-|-+
  3 +---+-- area ---+---+  +--- column axis
    |   | x | x | x |   |  |
  4 +---+---+---+---+---+<-|--- line
    |   |   |   |   |   |  |
  5 +---+---+---+---+---+ <+
#+end_example

** Grid Container

- grid-template :: Defines the rows and columns of the grid. Sets track sizes.
  Line names are optional.
  
#+begin_example
  grid-template-columns: 1fr 2fr 1fr;
  grid-template-rows: repeat(3, 1fr);

       1fr   2fr  1fr
      +---+-------+---+
  1fr |   |       |   |
      +---+-------+---+
  1fr |   |       |   |
      +---+-------+---+
  1fr |   |       |   |
      +---+-------+---+

  grid-template-areas: "X X X"
                       "Y Y Z";

  +----------+
  | X        |
  +------+---+
  | Y  Y | Z |
  +------+---+
#+end_example

- grid-gap :: Sets the size of the grid lines, the gutters between columns
  and rows.

#+begin_example
  gap: 20px 10px

  +---+-+---+-+---+
  | x | | x | | x |
  +---+ +---+ +---+
  |               | <- 20px
  +---+ +---+ +---+
  | x | | x | | x |
  +---+-+---+-+---+
       ^
       |
      10px
#+end_example

- justify-items :: Sets alignment along the row axis.

#+begin_example
  +-----------+-----------+
  |+---+      |+---+      |
  || x |      || x |      |
  |+---+      |+---+      |
  +-----------+-----------+ start
  |+---+      |+---+      |
  || x |      || x |      |
  |+---+      |+---+      |
  +-----------+-----------+

  +-----------+-----------+
  |      +---+|      +---+|
  |      | x ||      | x ||
  |      +---+|      +---+|
  +-----------+-----------+ end
  |      +---+|      +---+|
  |      | x ||      | x ||
  |      +---+|      +---+|
  +-----------+-----------+

  +-----------+-----------+
  |   +---+   |   +---+   |
  |   | x |   |   | x |   |
  |   +---+   |   +---+   |
  +-----------+-----------+ center
  |   +---+   |   +---+   |
  |   | x |   |   | x |   |
  |   +---+   |   +---+   |
  +-----------+-----------+

  +-----------+-----------+
  |+---------+|+---------+|
  || x       ||| x       ||
  |+---------+|+---------+|
  +-----------+-----------+ stretch
  |+---------+|+---------+|
  || x       ||| x       ||
  |+---------+|+---------+|
  +-----------+-----------+
#+end_example

- align-items :: Sets alignment along the column axis.

#+begin_example
  +-------+-------+
  | +---+ | +---+ |
  | | x | | | x | |
  | +---+ | +---+ |
  |       |       |
  |       |       |
  +-------+-------+ start
  | +---+ | +---+ |
  | | x | | | x | |
  | +---+ | +---+ |
  |       |       |
  |       |       |
  +-------+-------+

  +-------+-------+
  |       |       |
  |       |       |
  | +---+ | +---+ |
  | | x | | | x | |
  | +---+ | +---+ |
  +-------+-------+ end
  |       |       |
  |       |       |
  | +---+ | +---+ |
  | | x | | | x | |
  | +---+ | +---+ |
  +-------+-------+

  +-------+-------+
  |       |       |
  | +---+ | +---+ |
  | | x | | | x | |
  | +---+ | +---+ |
  |       |       |
  +-------+-------+ center
  |       |       |
  | +---+ | +---+ |
  | | x | | | x | |
  | +---+ | +---+ |
  |       |       |
  +-------+-------+

  +-------+-------+
  | +---+ | +---+ |
  | | x | | | x | |
  | |   | | |   | |
  | |   | | |   | |
  | +---+ | +---+ |
  +-------+-------+ stretch
  | +---+ | +---+ |
  | | x | | | x | |
  | |   | | |   | |
  | |   | | |   | |
  | +---+ | +---+ |
  +-------+-------+
#+end_example

- grid-auto-flow :: Defines automatic placement of grid items that aren't
  placed explicitly.

#+begin_example
     +---+ +---+ +---+
     | 1 | | 2 | | 3 | -+
     +---+ +---+ +---+  |
  +---------------------+ row
  |  +---+ +---+ +---+
  +> | 4 | | 5 | | 6 |
     +---+ +---+ +---+

            +---+
            |   V
     +---+  | +---+ +---+
     | 1 |  | | 3 | | 5 |
     +---+  | +---+ +---+ column
     +---+  | +---+ +---+
     | 2 | -+ | 4 | | 6 |
     +---+    +---+ +---+

     +---------+ +---+
     |    1    | | 3 |
     +---------+ +---+
     +---------+ +---+
     |    2    | | 4 |    row dense
     +---------+ +---+
     +---+ +---+
     | 5 | | 6 |
     +---+ +---+

     +---------+ +---+
     |    1    | | 5 |
     +---------+ +---+
     +---------+ +---+
     |    2    | | 6 |    column dense
     +---------+ +---+
     +---+ +---+
     | 3 | | 4 |
     +---+ +---+
#+end_example

- justify-content :: Justifies all grid content along the row axis if the total grid
  size is smaller than its container.

#+begin_example
  +-------------------------+
  |+---+---+---+            |
  || x | x | x |            |
  |+---+---+---+            |
  || x | x | x |            | start
  |+---+---+---+            |
  |                         |
  |                         |
  +-------------------------+

  +-------------------------+
  |            +---+---+---+|
  |            | x | x | x ||
  |            +---+---+---+|
  |            | x | x | x || end
  |            +---+---+---+|
  |                         |
  |                         |
  +-------------------------+

  +-------------------------+
  |      +---+---+---+      |
  |      | x | x | x |      |
  |      +---+---+---+      |
  |      | x | x | x |      | center
  |      +---+---+---+      |
  |                         |
  |                         |
  +-------------------------+

  +-------------------------+
  |+-------+-------+-------+|
  || x     | x     | x     ||
  |+-------+-------+-------+|
  || x     | x     | x     || stretch
  |+-------+-------+-------+|
  |                         |
  |                         |
  +-------------------------+

  +-------------------------+
  |+---+     +---+     +---+|
  || x |     | x |     | x ||
  |+---+     +---+     +---+|
  || x |     | x |     | x || space-between
  |+---+     +---+     +---+|
  |                         |
  |                         |
  +-------------------------+

  +-------|-------|-------+
  | +---+ | +---+ | +---+ |
  | | x | | | x | | | x | |
  | +---+ | +---+ | +---+ |
  | | x | | | x | | | x | |   space-around
  | +---+ | +---+ | +---+ |
  |       |       |       |
  |       |       |       |
  +-------|-------|-------+

  +--|---|--|---|--|---|--+
  |  +---+  +---+  +---+  |
  |  | x |  | x |  | x |  |
  |  +---+  +---+  +---+  |
  |  | x |  | x |  | x |  |   space-evenly
  |  +---+  +---+  +---+  |
  |  |   |  |   |  |   |  |
  |  |   |  |   |  |   |  |
  +--|---|--|---|--|---|--+
#+end_example

- align-content :: Justifies all grid content along the column axis if the total grid
  size is smaller than its container.

#+begin_example
  +----------------------+
  |+---+---+---+         |
  || x | x | x |         |
  |+---+---+---+         |
  || x | x | x |         | start
  |+---+---+---+         |
  |                      |
  |                      |
  +----------------------+

  +----------------------+
  |                      |
  |                      |
  |+---+---+---+         |
  || x | x | x |         | end
  |+---+---+---+         |
  || x | x | x |         |
  |+---+---+---+         |
  +----------------------+

  +----------------------+
  |                      |
  |+---+---+---+         |
  || x | x | x |         |
  |+---+---+---+         | center
  || x | x | x |         |
  |+---+---+---+         |
  |                      |
  +----------------------+

  +----------------------+
  |+---+---+---+         |
  || x | x | x |         |
  ||   |   |   |         |
  |+---+---+---+         | stretch
  || x | x | x |         |
  ||   |   |   |         |
  |+---+---+---+         |
  +----------------------+

  +----------------------+
  |+---+---+---+         |
  || x | x | x |         |
  |+---+---+---+         |
  |                      | space-between
  |+---+---+---+         |
  || x | x | x |         |
  |+---+---+---+         |
  +----------------------+

  +----------------------+
  |                      |
  |+---+---+---+         |
  || x | x | x |         |
  |+---+---+---+         |
  |                      |
  ------------------------ space-around
  |                      |
  |+---+---+---+         |
  || x | x | x |         |
  |+---+---+---+         |
  |                      |
  +----------------------+

  +----------------------+
  |                      |
  -+---+---+---+----------
  || x | x | x |         |
  -+---+---+---+----------
  |                      | space-evenly
  -+---+---+---+----------
  || x | x | x |         |
  -+---+---+---+----------
  |                      |
  +----------------------+
#+end_example

** Grid Items

- justify-self :: Aligns an item inside a single cell along the row axis.

#+begin_example
  +-----------+-----------+
  |+---+      |           |
  || x |      |           |
  |+---+      |           |
  +-----------+-----------+ start
  |           |           |
  |           |           |
  |           |           |
  +-----------+-----------+

  +-----------+-----------+
  |      +---+|           |
  |      | x ||           |
  |      +---+|           |
  +-----------+-----------+ end
  |           |           |
  |           |           |
  |           |           |
  +-----------+-----------+

  +-----------+-----------+
  |   +---+   |           |
  |   | x |   |           |
  |   +---+   |           |
  +-----------+-----------+ center
  |           |           |
  |           |           |
  |           |           |
  +-----------+-----------+

  +-----------+-----------+
  |+---------+|           |
  || x       ||           |
  |+---------+|           |
  +-----------+-----------+ stretch
  |           |           |
  |           |           |
  |           |           |
  +-----------+-----------+
#+end_example

- align-self :: Aligns an item inside a single cell along the column axis.

#+begin_example
  +-------+-------+
  | +---+ |       |
  | | x | |       |
  | +---+ |       |
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  +-------+-------+ start
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  +-------+-------+

  +-------+-------+
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  | +---+ |       |
  | | x | |       |
  | +---+ |       |
  +-------+-------+ end
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  +-------+-------+

  +-------+-------+
  |       |       |
  |       |       |
  | +---+ |       |
  | | x | |       |
  | +---+ |       |
  |       |       |
  |       |       |
  +-------+-------+ center
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  +-------+-------+

  +-------+-------+
  | +---+ |       |
  | | x | |       |
  | |   | |       |
  | |   | |       |
  | |   | |       |
  | |   | |       |
  | +---+ |       |
  +-------+-------+ stretch
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  |       |       |
  +-------+-------+
#+end_example

- grid-column :: Sets an item's location by start and end column coordinates.
  
- grid-row :: Sets an item's location by start and end row coordinates.

#+begin_example
  grid-column: 2 / 4
  or
  grid-column: 2 / span 2

    1      2      3      4
  1 +------+------+------+
    |      |+-----------+|
    |      || x         ||
    |      |+-----------+|
  2 +------+------+------+
    |      |      |      |
    |      |      |      |
    |      |      |      |
  3 +------+------+------+

  grid-row: 1 / 3
  or
  grid-row: 1 / span 2

    1      2      3      4
  1 +------+------+------+
    |+----+|      |      |
    || x  ||      |      |
    ||    ||      |      |
  2 +|    |+------+------+
    ||    ||      |      |
    ||    ||      |      |
    |+----+|      |      |
  3 +------+------+------+
#+end_example

