* Regular Expressions and Finite-State Automata

** Sources

| source                       | author                        |
|------------------------------+-------------------------------|
| *Foundations of Computation* | Carol Critchlow and David Eck |
| *Regular Language*           | Wikipedia                     |

** Regular Languages

- alphabet (Σ) :: A finite, non-empty set of symbols.

- symbols (a, b, c, ...) :: The elements of an alphabet.

- string (u, v, w, ...) :: A finite sequence of symbols from an alphabet.
  Called a *string over an alphabet*.

  - *Σ = {0, 1}* is an alphabet, and *001*, *1*, and *11* are all strings over *Σ*.

- empty set (Ø) :: The set containing no strings.

- empty string (ε) :: A string of length *0*. The identity element for string concatenation.

- Σ\star{} :: The set of all strings over alphabet *Σ*, including *ε*.

  - For *Σ* with *n* elements, there is *1* string with *0* symbols, *n* strings with *1* symbol,
    *n^{2}* strings with *2* symbols, *n^{3}* strings with *3* symbols, etc.

#+begin_example
  Σ  = { 0, 1 }
  Σ⁰ = { ε }
  Σ¹ = { 0, 1 }
  Σ² = { 00, 01, 10, 11 }
  Σ³ = { 000, 001, 010, 011, 100, 101, 110, 111 }
  ...
  Σ* = { ε, 0, 1, 00, 01, ... }
#+end_example

- language (L) :: Any subset of *Σ\star{}*. A collection of strings over alphabet *Σ*.

  - A language over an alphabet *Σ* is a subset of *Σ\star{}*. Thus, a language over *Σ* is an element
    of *P(Σ\star{})*, the power set of *Σ\star{}*.

** Regular Expressions

A language is *regular* if it is generated by a regular expression. The union of two regular languages
is regular. The concatenation of regular languages is regular. The Kleene closure of a regular language
is regular.

| regular expression | regular language                          | name           |
|--------------------+-------------------------------------------+----------------|
| Ø                  | {}                                        | empty set      |
| ε                  | { "" }                                    | epsilon        |
| a                  | { "a" }                                   | singleton      |
| s \vert{} t        | L(s) ∪ L(t)                               | union          |
| st or s • t        | { s • t : s ∈ L(s) ∧ t ∈ L(t) }           | concatenation  |
| s*                 | { "" } ∪ { s • s : s ∈ L(s) ∧ s ∈ L(s*) } | Kleene closure |

*** Formal Definition

The collection of regular languages over an alphabet *Σ* is defined recursively as follows:

1. The empty language *Ø* is a regular language.

2. For each *a ∈ Σ*, the singleton language *{a}* is a regular language.

3. If *A* is a regular language, *A\star{}* is a regular language. Due to this, the empty string
   language *ε* is also regular.

4. If *A* and *B* are regular languages, then *A ∪ B* and *A • B* are regular languages.

5. No other languages over *Σ* are regular.

*** Language Generated by Regular Expression

- L(Φ) = Ø

- L(ε) = { ε }

- L(a) = { a }

- L(r₁ | r₂) = L(r₁) ∪ L(r₂)

- L(r₁ • r₂) = L(r₁) • L(r₂)

- L(r\star{}) = L(r)\star{} = { ε } ∪ L(r) ∪ L(r)* ...

- L((r)) = L(r)

#+begin_example
  L(r) = { ε, a, b, aa, ab, bb, aaa, aab, abb, bbb, ... }
  where Σ             = { a, b }
        r             = a*b*
        L(a*) • L(b*) = { x • y | x ∈ L(a*) ∧ y ∈ L(b*) }
        L(a*)         = { ε, a, aa, aaa, ... }
        L(b*)         = { ε, b, bb, bbb, ... }
        L(a)          = { a }
        L(b)          = { b }
#+end_example

*** Operators

| precedence | name          | operator  |
|------------+---------------+-----------|
|          1 | alternation   | *\vert{}* |
|          2 | concatenation | *•*       |
|          3 | Kleene star   | *\star{}* |

** Finite-State Automata

- finite-state automaton (FSA) :: A machine that takes as input a finite string of symbols from
  alphabet *Σ*. There is a finite set of *states* in which the machine can find itself. The state
  it is in before consuming input is called the *start state*. Some of the states are *accepting*
  or *final*. If the machine ends in such a state after completely consuming an input string, the
  string is said to be *accepted* by the machine.

- transition function :: Determines the next state according to the current state and symbol.

*** Deterministic Finite-State Automaton

*M* is specified by five components: *M = (Q, Σ, δ, q₀, F)* where

- Q :: A finite set of states.

- Σ :: Input alphabet, a finite set.

- δ : Q × Σ → Q :: The transition function.

- q₀ ∈ Q :: The start state.

- F ⊆ Q :: A subset of *Q*. The states designated as *final* or *accepting* states.

*δ* is a transition function that takes *(state, symbol)* pairs and maps each one to a state:
*δ : Q × Σ → Q*. The declaration *δ(q, a) = qp* means that if a machine is in state *q* and
the input symbol *a* is consumed, then the machine will move to state *qp*. The function *δ*
must be a total function, meaning that *δ(q, a)* must be defined for every state *q* and every
input symbol *a*. Given the current input symbol, there is only one possible move the machine
can make.

The language accepted by *M*, denoted *L(M)*, is the set of all strings *w ∈ Σ\star{}* that are
accepted by *M: L(M) = { w ∈ Σ\star{} | δ\star{}(q₀, w) ∈ F }*.

*δ\star{}(q, w)* denotes the state that a DFA will be in if it starts in state *q* and consumes
input string *w*.

*** Non-deterministic Finite-State Automaton

*M* is specified by five components: *M = (Q, Σ, δ, q₀, F)* where

- Q :: A finite set of states.

- Σ :: Input alphabet, a finite set.

- δ : Q × (Σ ∪ {ε}) → P(Q) :: The transition function.

- q₀ ∈ Q :: The start state.

- F ⊆ Q :: A subset of *Q*. The states designated as *final* or *accepting* states.

*δ* is a transition function that takes *(state, input symbol)* pairs and maps each one to a set
of states. To say *δ(q, a) = { q₁, q₂, ..., qn }* means that if the machine is in state *q* and
the input symbol *a* is consumed, then the machine may move directly into any one of states
*q₁, q₂, ..., qn*. The function *δ* must also be defined for every *(state, ε)* pair, where state
may change but no input is consumed. The formal description of *δ* is *δ: Q × (Σ ∪ {ε}) → P(Q)*.

The language accepted by *M*, denoted *L(M)*, is the set of all strings *w ∈ Σ\star{}* that are
accepted by *M: L(M) = { w ∈ Σ\star{} | δ\star{}(q₀, w) ∩ F ≠ Ø }*.

#+begin_example
   === State Machine Graph ==

    + 0 +    + 0 +     + 0 +
    V   |    V   |     V   |
    +---+    +---+    +=====+
   >| x |-1->| y |-1->|| z ||
    +---+    +---+    +=====+
                       ^   |
                       + 1 +

  === State Machine Table ===

    +- state
    V
  +-----------+
  |   | 0 | 1 | <- input
  |---+---+---|
  | x | x | y |
  |---+---+---|
  | y | y | z |
  |---+---+---|
  | z | z | z |
  +-----------+

  === State Machine Tuple ===

  M = (Q, Σ, δ, q₀, F)
  where Q = { x, y, z}
        Σ = { 0, 1 }
        δ = { (x, 0) -> x,
              (y, 0) -> y,
              (z, 0) -> z,
              (x, 1) -> y,
              (y, 1) -> z,
              (z, 1) -> z }
        q₀ = x
        F  = { z }
#+end_example

*** NFA to DFA Conversion

The epsilon closure *E(q)* of a state *q* in *Q* is the union of the set *{q}* with the set of all states
that can be reached from *q* via one or more *ε* transitions.

If *R* is a set of states from *Q*, the epsilon closure *E(R)* is defined as the union of the epsilon
closures of all the states in *R*.

1. The set of states of the DFA is *P(Q)*, the power set of states *Q* in the original NFA.

2. The start state of the DFA is *E({q₀})*, where *q₀* is the original start state of the NFA.

3. For sets *R* in *P(Q)* and input characters *c ∈ Σ*, the transition function *δ_{n}* of the DFA is defined
   in terms of the transition function *δ* of the NFA by *δ_{n}(R,c) = U_{r ∈ R} E(δ(r,c))*.

The set of accepting states *F* of the DFA is defined to be the set of all states containing at least one
final state of the NFA.
