* Global Allocation in Rust

** Sources

| source                                        | author        |
|-----------------------------------------------+---------------|
| *GlobalAlloc: Rust Standard Library (1.97.1)* | rust-lang.org |
| *ptr: Rust Standard Library (1.97.1)*         | rust-lang.org |

All the sections below are examples and text copied from the Rust Standard Library.

** ~GlobalAlloc~ Trait

#+begin_src rust
  use crate::alloc::Layout;
  use crate::{cmp, ptr};

  #[stable(feature = "global_alloc", since = "1.28.0")]
  pub unsafe trait GlobalAlloc {
      #[stable(feature = "global_alloc", since = "1.28.0")]
      unsafe fn alloc(&self, layout: Layout) -> *mut u8;

      #[stable(feature = "global_alloc", since = "1.28.0")]
      unsafe fn dealloc(&self, ptr: *mut u8, layout: Layout);

      #[stable(feature = "global_alloc", since = "1.28.0")]
      unsafe fn alloc_zeroed(&self, layout: Layout) -> *mut u8 {
          let size = layout.size();
          // SAFETY: the safety contract for `alloc` must be upheld by the caller.
          let ptr = unsafe { self.alloc(layout) };
          if !ptr.is_null() {
              // SAFETY: as allocation succeeded, the region from `ptr`
              // of size `size` is guaranteed to be valid for writes.
              unsafe { ptr::write_bytes(ptr, 0, size) };
          }
          ptr
      }

      #[stable(feature = "global_alloc", since = "1.28.0")]
      unsafe fn realloc(&self, ptr: *mut u8, layout: Layout, new_size: usize) -> *mut u8 {
          // SAFETY: the caller must ensure that the `new_size` does not overflow.
          // `layout.align()` comes from a `Layout` and is thus guaranteed to be valid.
          let new_layout = unsafe { Layout::from_size_align_unchecked(new_size, layout.align()) };
          // SAFETY: the caller must ensure that `new_layout` is greater than zero.
          let new_ptr = unsafe { self.alloc(new_layout) };
          if !new_ptr.is_null() {
              // SAFETY: the previously allocated block cannot overlap the newly allocated block.
              // The safety contract for `dealloc` must be upheld by the caller.
              unsafe {
                  ptr::copy_nonoverlapping(ptr, new_ptr, cmp::min(layout.size(), new_size));
                  self.dealloc(ptr, layout);
              }
          }
          new_ptr
      }
  }
#+end_src

** Implement ~GlobalAlloc~ for ~System~

#+begin_src rust
  use super::{MIN_ALIGN, realloc_fallback};
  use crate::alloc::{GlobalAlloc, Layout, System};
  use crate::ptr;

  #[stable(feature = "alloc_system_type", since = "1.28.0")]
  unsafe impl GlobalAlloc for System {
      #[inline]
      unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
          // jemalloc provides alignment less than MIN_ALIGN for small allocations.
          // So only rely on MIN_ALIGN if size >= align.
          if layout.align() <= MIN_ALIGN && layout.align() <= layout.size() {
              unsafe { libc::malloc(layout.size()) as *mut u8 }
          } else {
              // `posix_memalign` returns a non-aligned value if supplied a very
              // large alignment on older versions of Apple's platforms (unknown
              // exactly which version range, but the issue is definitely
              // present in macOS 10.14 and iOS 13.3).
              #[cfg(target_vendor = "apple")]
              {
                  if layout.align() > (1 << 31) {
                      return ptr::null_mut();
                  }
              }
              unsafe { aligned_malloc(&layout) }
          }
      }

      #[inline]
      unsafe fn alloc_zeroed(&self, layout: Layout) -> *mut u8 {
          // See the comment above in `alloc` for why this check looks the way it does.
          if layout.align() <= MIN_ALIGN && layout.align() <= layout.size() {
              unsafe { libc::calloc(layout.size(), 1) as *mut u8 }
          } else {
              let ptr = unsafe { self.alloc(layout) };
              if !ptr.is_null() {
                  unsafe { ptr::write_bytes(ptr, 0, layout.size()) };
              }
              ptr
          }
      }

      #[inline]
      unsafe fn dealloc(&self, ptr: *mut u8, _layout: Layout) {
          unsafe { libc::free(ptr as *mut libc::c_void) }
      }

      #[inline]
      unsafe fn realloc(&self, ptr: *mut u8, layout: Layout, new_size: usize) -> *mut u8 {
          if layout.align() <= MIN_ALIGN && layout.align() <= new_size {
              unsafe { libc::realloc(ptr as *mut libc::c_void, new_size) as *mut u8 }
          } else {
              // Fallback mirrors default implementation in GlobalAlloc trait.
              unsafe { realloc_fallback(self, ptr, layout, new_size) }
          }
      }
  }

  cfg_if::cfg_if! {
      // We use posix_memalign wherever possible, but some targets have very incomplete POSIX coverage
      // so we need a fallback for those.
      if #[cfg(any(
          target_os = "horizon",
          target_os = "vita",
      ))] {
          #[inline]
          unsafe fn aligned_malloc(layout: &Layout) -> *mut u8 {
              unsafe { libc::memalign(layout.align(), layout.size()) as *mut u8 }
          }
      } else {
          #[inline]
          #[cfg_attr(target_os = "vxworks", allow(unused_unsafe))]
          unsafe fn aligned_malloc(layout: &Layout) -> *mut u8 {
              let mut out = ptr::null_mut();
              // We prefer posix_memalign over aligned_alloc since it is more widely available, and
              // since with aligned_alloc, implementations are making almost arbitrary choices for
              // which alignments are "supported", making it hard to use. For instance, some
              // implementations require the size to be a multiple of the alignment (wasi emmalloc),
              // while others require the alignment to be at least the pointer size (Illumos, macOS).
              // posix_memalign only has one, clear requirement: that the alignment be a multiple of
              // `sizeof(void*)`. Since these are all powers of 2, we can just use max.
              let align = layout.align().max(crate::mem::size_of::<usize>());
              let ret = unsafe { libc::posix_memalign(&mut out, align, layout.size()) };
              if ret != 0 { ptr::null_mut() } else { out as *mut u8 }
          }
      }
  }
#+end_src

** Implement ~GlobalAlloc~ for ~SimpleAlloc~

An allocation is a subset of program memory which is addressable from Rust,
and within which pointer arithmetic is possible. Examples of allocations
include heap allocations, stack-allocated variables, statics, and consts.
The safety preconditions of some Rust operations - such as ~offset~ and
field projections (~expr.field~) - are defined in terms of the allocations
on which they operate.

An allocation has a base address, a size, and a set of memory addresses.
It is possible for an allocation to have zero size, but such an allocation
will still have a base address. The base address of an allocation is not
necessarily unique. While it is currently the case that an allocation always
has a set of memory addresses which is fully contiguous (i.e., has no "holes"),
there is no guarantee that this will not change in the future.

Allocations must behave like "normal" memory: in particular, reads must not
have side-effects, and writes must become visible to other threads using
the usual synchronization primitives.

For any allocation with ~base~ address, ~size~, and a set of ~addresses~,
the following are guaranteed:

- For all addresses ~a~ in ~addresses~, ~a~ is in the range ~base .. (base + size)~
  (note that this requires ~a < base + size~, not ~a <= base + size~)

- base is not equal to ~null()~ (i.e., the address with the numerical value ~0~)

- ~base + size <= usize::MAX~

- ~size <= isize::MAX~

As a consequence of these guarantees, given any address ~a~ within the set
of addresses of an allocation:

- It is guaranteed that ~a - base~ does not overflow ~isize~

- It is guaranteed that ~a - base~ is non-negative

- It is guaranteed that, given ~o = a - base~ (i.e., the offset of a within the allocation),
  ~base + o~ will not wrap around the address space (in other words, will not overflow ~usize~)

#+begin_src rust
  // Example pulled from the alloc module in the Rust Standard Library
  use std::alloc::{GlobalAlloc, Layout};
  use std::cell::UnsafeCell;
  use std::ptr::null_mut;
  use std::sync::atomic::{AtomicUsize, Ordering::Relaxed};

  const ARENA_SIZE: usize = 128 * 1024;
  const MAX_SUPPORTED_ALIGNMENT: usize = 4096;
  
  #[repr(C, align(4096))]
  struct SimpleAllocator {
      arena: UnsafeCell<[u8; ARENA_SIZE]>,
      // Allocate from the top, counting down.
      remaining: AtomicUsize,
  }

  #[global_allocator]
  static ALLOCATOR: SimpleAllocator = SimpleAllocator {
      arena: UnsafeCell::new([0x55; ARENA_SIZE]),
      remaining: AtomicUsize::new(ARENA_SIZE),
  };

  unsafe impl Sync for SimpleAllocator {}

  unsafe impl GlobalAlloc for SimpleAllocator {
      unsafe fn alloc(&self, layout: Layout) -> *mut u8 {
          let size = layout.size();
          let align = layout.align();

          // "Layout" demands alignment be a non-zero, power of two. Therefore, we can safely
          // use a mask to ensure alignment without worrying about undefined behavior.
          let align_mask_to_round_down = !(align - 1);

          if align > MAX_SUPPORTED_ALIGNMENT {
              return null_mut();
          }

          let mut allocated = 0;
          if self
              .remaining
              .try_update(Relaxed, Relaxed, |mut remaining| {
                  if size > remaining {
                      return None;
                  }
                  remaining -= size;
                  remaining &= align_mask_to_round_down;
                  allocated = remaining;
                  Some(remaining)
              })
              .is_err()
          {
              return null_mut();
          };
          unsafe { self.arena.get().cast::<u8>().add(allocated) }
      }
      unsafe fn dealloc(&self, _ptr: *mut u8, _layout: Layout) {}
  }

  fn main() {
      let _text = format!("Allocate a string!");
      let currently = ALLOCATOR.remaining.load(Relaxed);
      println!("memory allocated so far: {}", ARENA_SIZE - currently);
  }
#+end_src
