* UTF-8

** Sources

| source                    | author          |
|---------------------------+-----------------|
| *Unicode*                 | unicode.org     |
| *UTF-8*                   | wikipedia.org   |
| *UTF-8, Explained Simply* | Nic Barker      |
| *UTF-8 Decoder DFA*       | Bjöern Höehrman |

** Overview

- UTF-8 :: Unicode Transformation Format. 8-bit base size.

- Encodes up to 4 bytes

- ASCII compatible

- Self synchronizing

- Compressible

#+begin_example
  === Bit Base Sizes ===

           +---+---+---+---+
  UTF-8  = | x |   |   |   |
           +---+---+---+---+
           +---+---+---+---+
  UTF-16 = | x | x |   |   |
           +---+---+---+---+
           +---+---+---+---+
  UTF-32 = | x | x | x | x |
           +---+---+---+---+
#+end_example

| code point | decimal | character | utf-8 encoding                        | utf-8 (hex)   |
|------------+---------+-----------+---------------------------------------+---------------|
| U+0041     |      65 | A         | ~01000001~                            | ~41~          |
| U+03BB     |     955 | λ         | ~11001110 10111011~                   | ~CE BB~       |
| U+2318     |    8984 | ⌘         | ~11100010 10001100 10011000~          | ~E2 8C 98~    |
| U+1F44D    |  128077 | 👍        | ~11110000 10011111 10010001 10001101~ | ~F0 9F 91 8D~ |

#+begin_example
 +---+
 | 0 | Single-Byte ASCII Codepoint
 +---+
 +---+
 | 1 | Multi-Byte Codepoint
 +---+
 +---+---+
 | 1 | 1 | Lead Byte
 +---+---+
 +---+---+
 | 1 | 0 | Continuation Byte
 +---+---+

 === UTF-8 Encoding: ⌘ ===

    +- Multi-Byte Codepoint
    |    +- 3-Byte Codepoint
    |    |      +-----------+-------------+---------+
    |    |      |           |             |         |
    |    |  +------+    +--------+    +--------+    |
  +----------------+-------------+-------------+    |
  | 1 | 110 | 0010 | 10 | 001100 | 10 | 011000 |    |
  +----------------+-------------+-------------+    |
  ^----------------^---------------------------^    |
     Leading Byte       Continuation Bytes          |
            ^                                       |
            |                                       |
   (Synchronization Point)                          |
                                      +-------------+
  === Code Point: ⌘ ===               |
                          +-----------------------+
  +-----------+-----------+-----------+-----------+
  | 0000 0000 | 0000 0000 | 0010 0011 | 0001 1000 | <- UTF-8 standard mandates that
  +-----------+-----------+-----------+-----------+    the shortest encoding of a
                                                       codepoint be used.
#+end_example

** Byte Map

|   | 0   | 1   | 2   | 3   | 4   | 5   | 6   | 7   | 8   | 9  | A   | B   | C       | D  | E  | F   |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| 0 | NUL | SOH | STX | ETX | EOT | ENQ | ACK | BEL | BS  | HT | LF  | VT  | FF      | CR | SO | SI  |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| 1 | DLE | DC1 | DC2 | DC3 | DC4 | NAK | SYN | ETB | CAN | EM | SUB | ESC | FS      | GS | RS | US  |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| 2 | SP  | !   | "   | #   | $   | %   | &   | '   | (   | )  | *   | +   | ,       | -  | .  | /   |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| 3 | 0   | 1   | 2   | 3   | 4   | 5   | 6   | 7   | 8   | 9  | :   | ;   | <       | =  | >  | ?   |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| 4 | @   | A   | B   | C   | D   | E   | F   | G   | H   | I  | J   | K   | L       | M  | N  | O   |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| 5 | P   | Q   | R   | S   | T   | U   | V   | W   | X   | Y  | Z   | [   | \       | ]  | ^  | _   |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| 6 | `   | a   | b   | c   | d   | e   | f   | g   | h   | i  | j   | k   | l       | m  | n  | o   |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| 7 | p   | q   | r   | s   | t   | u   | v   | w   | x   | y  | z   | {   | \vert{} | }  | ~  | DEL |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| 8 |     |     |     |     |     |     |     |     |     |    |     |     |         |    |    |     |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| 9 |     |     |     |     |     |     |     |     |     |    |     |     |         |    |    |     |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| A |     |     |     |     |     |     |     |     |     |    |     |     |         |    |    |     |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| B |     |     |     |     |     |     |     |     |     |    |     |     |         |    |    |     |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| C | 2   | 2   | 2   | 2   | 2   | 2   | 2   | 2   | 2   | 2  | 2   | 2   | 2       | 2  | 2  | 2   |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| D | 2   | 2   | 2   | 2   | 2   | 2   | 2   | 2   | 2   | 2  | 2   | 2   | 2       | 2  | 2  | 2   |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| E | 3   | 3   | 3   | 3   | 3   | 3   | 3   | 3   | 3   | 3  | 3   | 3   | 3       | 3  | 3  | 3   |
|---+-----+-----+-----+-----+-----+-----+-----+-----+-----+----+-----+-----+---------+----+----+-----|
| F | 4   | 4   | 4   | 4   | 4   | 4   | 4   | 4   | 5   | 5  | 5   | 5   | 6       | 6  |    |     |

*** Legend

| Type                 | Range                        |
|----------------------+------------------------------|
| ASCII control        | ~{ 00-2F } ∪ { 7F }~         |
|----------------------+------------------------------|
| ASCII character      | ~{ 20-7E }~                  |
|----------------------+------------------------------|
| Continuation Byte    | ~{ 80-BF }~                  |
|----------------------+------------------------------|
| First of N-bytes     | ~{ C2-F3 } \ { E0, ED, F0 }~ |
|----------------------+------------------------------|
| Invalid Continuation | ~{ E0, ED, F0, F4 }~         |
|----------------------+------------------------------|
| Unused               | ~{ C0-C1 } ∪ { F5-FF }~      |

** UTF-8 Decoder DFA (C99)

#+begin_quote
  "UTF-8 is a variable length character encoding. To decode a character one or more bytes
   have to be read from a string. The decode function implements a single step in this
   process. It takes two parameters maintaining state and a byte, and returns the state
   achieved after processing the byte. Specifically, it returns the value ~UTF8_ACCEPT~ (~0~)
   if enough bytes have been read for a character, ~UTF8_REJECT~ (~1~) if the byte is
   not allowed to occur at its position, and some other positive value if more bytes
   have to be read.

   When decoding the first byte of a string, the caller must set the state variable
   to ~UTF8_ACCEPT~. If, after decoding one or more bytes the state ~UTF8_ACCEPT~ is
   reached again, then the decoded Unicode character value is available through
   the ~codep~ parameter. If the state ~UTF8_REJECT~ is entered, that state will
   never be exited unless the caller intervenes..."

  — *bjoern.hoehrmann.de/utf-8/decoder/dfa/*, Bjöern Höehrman
#+end_quote

#+begin_src c
  // Copyright (c) 2008-2009 Bjoern Hoehrmann <bjoern@hoehrmann.de>
  // See bjoern.hoehrmann.de/utf-8/decoder/dfa/ for details.

  #define UTF8_ACCEPT 0
  #define UTF8_REJECT 1

  static const uint8_t utf8d[] = {
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, // 00..1f
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, // 20..3f
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, // 40..5f
    0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0, // 60..7f
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9,9, // 80..9f
    7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7,7, // a0..bf
    8,8,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2,2, // c0..df
    0xa,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x3,0x4,0x3,0x3, // e0..ef
    0xb,0x6,0x6,0x6,0x5,0x8,0x8,0x8,0x8,0x8,0x8,0x8,0x8,0x8,0x8,0x8, // f0..ff
    0x0,0x1,0x2,0x3,0x5,0x8,0x7,0x1,0x1,0x1,0x4,0x6,0x1,0x1,0x1,0x1, // s0..s0
    1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,1,1,1,1,1,0,1,0,1,1,1,1,1,1, // s1..s2
    1,2,1,1,1,1,1,2,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1, // s3..s4
    1,2,1,1,1,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,1,3,1,3,1,1,1,1,1,1, // s5..s6
    1,3,1,1,1,1,1,3,1,3,1,1,1,1,1,1,1,3,1,1,1,1,1,1,1,1,1,1,1,1,1,1, // s7..s8
  };

  uint32_t inline
  decode(uint32_t* state, uint32_t* codep, uint32_t byte) {
    uint32_t type = utf8d[byte];

    *codep = (*state != UTF8_ACCEPT) ?
      (byte & 0x3fu) | (*codep << 6) :
      (0xff >> type) & (byte);

    *state = utf8d[256 + *state*16 + type];
    return *state;
  }
#+end_src

*** Canonical UTF-8 Automaton

#+begin_example
                                              2 = c2..df
             +--------------------------------------------------------------------------+
             |               3 = e1..ec, ee..ef                                         |
  0 = 00..7f |+----------------------------------------------+                          |
   +-------+ ||      5 = f4..f4  +---+                       |                          |
   |       V ||   +------------->| 8 |-+                     |                          |
  +------------+  |              +---+ |       1 = 80..8f    V                          |
  |+----------+|--+  6 = f1..f3  +---+ +------------------>+---+                        |
  ||     0    ||---------------->| 7 |---1, 7, 9 = 80..bf->| 3 |--+                     |
  |+----------+|--+              +---+ +------------------>+---+  |                     V
  +------------+  | 11 = f0..f0  +---+ |    7, 9 = 90..bf         | 1, 7, 9 = 80..bf  +---+
    ^ | |         +------------->| 6 |-+                          +------------------>| 2 |
    | | |                        +---+                                                +---+
    | | |                                                                              ^^|
    | | |            10 = e0..e0             +---+              7 = a0..bf             |||
    | | +----------------------------------->| 4 |-------------------------------------+||
    | |                                      +---+                                      ||
    | |               4 = ed..ed             +---+           1, 9 =  80..9f             ||
    | +------------------------------------->| 5 |--------------------------------------+|
    |                                        +---+                                       |
    |                                                                                    |
    |                                   1, 7, 9 = 80..bf                                 |
    +------------------------------------------------------------------------------------+

  legend: CLASS = RANGE
#+end_example
