* Lua's C API 5.5

** Sources

| source                                           | author                                                                 |
|--------------------------------------------------+------------------------------------------------------------------------|
| *Lua Manual* 5.5                                 | Roberto Ierusalimschy, Luiz Henrique de Figueiredo, and Waldemar Celes |
| *A Look at the Design of Lua*                    | Roberto Ierusalimschy, Luiz Henrique de Figueiredo, and Waldemar Celes |
| *Passing a Language through the Eye of a Needle* | Roberto Ierusalimschy, Luiz Henrique de Figueiredo, and Waldemar Celes |
| *Programming in Lua*                             | Roberto Ierusalimschy                                                  |
| *First-Class Functions in an Imperative World*   | Roberto Ierusalimschy                                                  |

** Introduction

Data transfer from C to Lua takes place through functions that receive C types, convert them
to Lua values, and place them on a virtual stack.

#+begin_quote
  "The Lua library defines no C global variables at all. It keeps all its state in the dynamic
   structure ~lua_State~; all functions inside Lua receive a pointer to this structure as an
   argument. This design makes Lua reentrant and ready to be used in multithreaded code...

   A major component in the communication between Lua and C is an omnipresent virtual stack.
   Almost all API calls operate on values on this stack. All data exchange from Lua to C and
   from C to Lua occurs through this stack. Moreover, we can use the stack to keep intermediate
   results, too...

   Lua manipulates this stack in a strict LIFO discipline (Last In, First Out). When we call Lua,
   it changes only the top part of the stack. Our C code has more freedom; specifically, it can
   inspect any element in the stack and even insert and delete elements at any position."

  — *Programming in Lua*, Roberto Ierusalimschy

  "All data exchange between Lua and C goes through a stack of Lua values. This stack has two purposes.
   The first one is to solve the mismatch between the dynamic typing in Lua and the static typing in C:
   all projections and injections between C values and Lua values go through the stack. The second
   purpose is to control garbage collection: C has direct access only to values in the stack, which
   cannot be collected while there."

  — *First-Class Functions in an Imperative World*, Roberto Ierusalimschy
#+end_quote

*** Lua State

#+begin_src c
  // === Per Thread State ===

  struct lua_State {
      // CommonHeader ------------+
      struct GCObject* next;  //  |
      lu_byte tt;             //  |
      lu_byte marked;         // <+
      // Type for thread status/error codes.
      TStatus status;
      // First free slot in the stack.
      StkIdRel top;
      // Reference to state shared by all threads. Contains mostly data
      // for memory allocation and garbage collection.
      struct global_State* l_G;
      // Call information for current function.
      CallInfo* ci;
      // End of stack (last element + 1)
      StkIdRel stack_last;
      // Stack base.
      StkIdRel stack;
      // List of open upvalues in this stack.
      UpVal* openupval;
      // List of to-be-closed variables.
      StkIdRel tbclist;
      // List of garbage-collectable objects.
      GCObject* gclist;
      // List of threads with open upvalues.
      struct lua_State* twups;
      // Current errory recovery point.
      struct lua_longjmp* errorJmp;
      // Call information for first level (C host).
      CallInfo base_ci;
      // Function to be called by the debugger.
      volatile lua_Hook hook;
      // Current error handling function (stack index).
      ptrdiff_t errfunc;
      // Number of nested, (non-yieldable | C) calls.
      l_uint32 nCcalls;
      // Last program counter traced.
      int oldpc;
      // Number of items in call information list.
      int nci;
      int basehookcount;
      int hookcount;
      volatile l_signalT hookmask;
      // Information about transferred values for (call | return) hooks.
      struct {
          // Offset of first value transferred.
          int ftransfer;
          // Number of values transferred.
          int ntransfer;
      } transferinfo;
  };
#+end_src

*** Pushing Elements

The API has a dedicated push function for each Lua type with a direct representation in C.

#+begin_src c
  // === API Signatures ===

  LUA_API void        (lua_pushnil)            (lua_State *L);
  LUA_API void        (lua_pushnumber)         (lua_State *L, lua_Number n);
  LUA_API void        (lua_pushinteger)        (lua_State *L, lua_Integer n);
  LUA_API const char *(lua_pushlstring)        (lua_State *L, const char *s, size_t len);
  LUA_API const char *(lua_pushexternalstring) (lua_State *L, const char *s, size_t len, lua_Alloc falloc, void *ud);
  LUA_API const char *(lua_pushstring)         (lua_State *L, const char *s);
  LUA_API const char *(lua_pushvfstring)       (lua_State *L, const char *fmt, va_list argp);
  LUA_API const char *(lua_pushfstring)        (lua_State *L, const char *fmt, ...);
  LUA_API void        (lua_pushcclosure)       (lua_State *L, lua_CFunction fn, int n);
  LUA_API void        (lua_pushboolean)        (lua_State *L, int b);
  LUA_API void        (lua_pushlightuserdata)  (lua_State *L, void *p);
  LUA_API int         (lua_pushthread)         (lua_State *L);

  // Ensures stack has space for at least "n" extra elements.
  LUA_API int         (lua_checkstack)         (lua_State *L, int n);

  // Similar to "lua_checkstack" but raises an error with the given message
  // if unable to complete operation.
  LUALIB_API void     (luaL_checkstack)        (lua_State *L, int n, const char *msg);

  // === Example Implementations ===

  // Push float of value "n" onto the stack.
  LUA_API void lua_pushnumber(lua_State* L, lua_Number n) {
      // "lua_lock" and "lua_unlock" are placeholders for what
      // would be a mutex in multi-threaded environments.
      lua_lock(L);
      // Set the top of the stack to the given value "n".
      setfltvalue(s2v(L->top.p), n);
      // Increment the top of the stack, checking for overflow.
      api_incr_top(L);
      lua_unlock(L);
  }

  // Convert StackValue to TValue.
  #define s2v(o) (&(o)->val)
  // Set type tag.
  #define settt_(o, t) ((o)->tt_ = (t))
  // Set Lua value of type float.
  #define setfltvalue(obj, x)      \
      {                            \
          TValue* io = (obj);      \
          val_(io).n = (x);        \
          settt_(io, LUA_VNUMFLT); \
      }

  // Ensures stack has space for at least "n" extra elements.
  LUA_API int lua_checkstack(lua_State* L, int n) {
      int res;
      CallInfo* ci;
      lua_lock(L);
      // Call information for current function.
      ci = L->ci;
      api_check(L, n >= 0, "negative 'n'");
      // If more space is needed, grow call stack.
      if (L->stack_last.p - L->top.p > n) {
          res = 1;
      } else {
          res = luaD_growstack(L, n, 0);
      }
      // Adjust call frame.
      if (res && ci->top.p < L->top.p + n) {
          ci->top.p = L->top.p + n;
      }
      lua_unlock(L);
      return res;
  }
#+end_src

*** Indexing Elements

#+begin_quote
  "To refer to elements on the stack, the API uses indices. The first element pushed on the stack
   has index 1, the next one has index 2, and so on. We can also access elements using the top of
   the stack as our reference, with negative indices."

   — *Programming in Lua*, Roberto Ierusalimschy
#+end_quote

#+begin_src c
  static void dump_stack(lua_State* L) {
      int i;
      // Stack depth
      int top = lua_gettop(L);
      // Traverse stack, bottom to top.
      for (i = 1; i <= top; i += 1) {
          int t = lua_type(L, i);
          switch (t) {
              case LUA_TSTRING: {
                  printf("'%s'", lua_tostring(L, i));
                  break;
              }
              case LUA_TBOOLEAN: {
                  printf(lua_toboolean(L, i) ? "true" : "false");
                  break;
              }
              case LUA_TNUMBER: {
                  if (lua_isinteger(L, i)) {
                      printf("%lld", lua_tointeger(L, i));
                  } else {
                      printf("%g", lua_tonumber(L, i));
                  }
                  break;
              }
              default: {
                  printf("%s", lua_typename(L, t));
                  break;
              }
          }
          // Separator
          printf(" ");
      }
      // End
      printf("\n");
  }
#+end_src

*** Basic Stack Manipulation

#+begin_src c
  // === API Signatures ===

  // Returns the number of elements on the stack, which is also the top element's index.
  LUA_API int  (lua_gettop)    (lua_State *L);

  // Sets the number of elements on the stack. lua_settop(L, 0) empties the stack.
  LUA_API void (lua_settop)    (lua_State *L, int idx);

  // Pushes onto the stack a copy of the element at the given index.
  LUA_API void (lua_pushvalue) (lua_State *L, int idx);

  // Rotates the stack elements from the given index to the top of the stack by "n" positions.
  LUA_API void (lua_rotate)    (lua_State *L, int idx, int n);

  // Copies the element at one index into another, leaving the original untouched.
  LUA_API void (lua_copy)      (lua_State *L, int fromidx, int toidx);

  // Removes element at given index, shifting elements above it to fill in the gap.
  #define lua_remove(L, idx)   (lua_rotate(L, (idx), -1), lua_pop(L, 1))

  // Inserts top element into given index, shifting elements above to open space.
  #define lua_insert(L, idx)   lua_rotate(L, (idx), 1)

  // Pops an element and sets it at the given index.
  #define lua_replace(L, idx)  (lua_copy(L, -1, (idx)), lua_pop(L, 1))

  // Pops n elements from the stack.
  #define lua_pop(L, n)        lua_settop(L, -(n) - 1)

  // === Example Implementations ===

  LUA_API int lua_gettop(lua_State* L) {
      return cast_int(L->top.p - (L->ci->func.p + 1));
  }

  LUA_API void lua_settop(lua_State* L, int idx) {
      CallInfo* ci;
      StkId func, newtop;
      ptrdiff_t diff;
      lua_lock(L);
      // Function call information.
      ci = L->ci;
      // Function pointer.
      func = ci->func.p;
      if (idx >= 0) {
          api_check(L, idx <= ci->top.p - (func + 1), "new top too large");
          // Offset from top of stack.
          diff = ((func + 1) + idx) - L->top.p;
          for (; diff > 0; diff--) {
              // Clear new slots. Set to nil value
              setnilvalue(s2v(L->top.p++));
          }
      } else {
          api_check(L, -(idx + 1) <= (L->top.p - (func + 1)), "invalid new top");
          diff = idx + 1;
      }
      api_check(L, L->tbclist.p < L->top.p, "previous pop of an unclosed slot");
      newtop = L->top.p + diff;
      if (diff < 0 && L->tbclist.p >= newtop) {
          lua_assert(ci->callstatus & CIST_TBC);
          newtop = luaF_close(L, newtop, CLOSEKTOP, 0);
      }
      // Adjust stack only after closing any upvalues.
      L->top.p = newtop;
      lua_unlock(L);
  }
#+end_src

| function                          | stack                                 |
|-----------------------------------+---------------------------------------|
| ~lua_State *L = luaL_newstate();~ | []                                    |
| ~lua_pushboolean(L, 1);~          | [ true ]                              |
| ~lua_pushnumber(L, 10);~          | [ true, 10 ]                          |
| ~lua_pushnil(L);~                 | [ true, 10, nil ]                     |
| ~lua_pushstring(L, "hello");~     | [ true, 10, nil, "hello" ]            |
| ~lua_pushvalue(L, -4);~           | [ true, 10, nil, "hello", true ]      |
| ~lua_replace(L, 3);~              | [ true, 10, true, "hello" ]           |
| ~lua_settop(L, 6);~               | [ true, 10, true, "hello", nil, nil ] |
| ~lua_rotate(L, 3, 1);~            | [ true, 10, nil, true, "hello", nil ] |
| ~lua_remove(L, -3);~              | [ true, 10, nil, "hello", nil ]       |
| ~lua_settop(L, -5);~              | [ true ]                              |
| ~lua_close(L);~                   |                                       |

** Memory Allocation

#+begin_quote
  "The Lua core does not assume anything about how to allocate memory. It calls neither ~malloc~ nor
   ~realloc~ to allocate memory. Instead, it does all its memory allocation and deallocation through
   one single allocation function, which the user must provide when she creates a Lua state."

  — *Programming in Lua*, Roberto Ierusalimschy
#+end_quote

The auxiliary function ~luaL_newstate~ creates a Lua state with a default allocation function.
This default function uses the standard functions ~malloc~, ~realloc~, and ~free~ from the C
standard library. The primitive ~lua_newstate~, on the other hand, requires that the user
provide their own allocation function, which provides resource management for the entire
Lua application.

#+begin_src c
  // "lua_newstate" takes two arguments: an allocation function and a user data.
  lua_State* lua_newstate(lua_Alloc f, void* ud);

  // All allocation functions must match the "lua_Alloc" type signature.
  // where ud    = user data
  //       ptr   = memory block address
  //       osize = original block size
  //       nsize = requested block size
  typedef void* (*lua_Alloc)(void* ud, void* ptr, size_t osize, size_t nsize);

  // "luaL_newstate" as defined in "lauxlib.c".
  void* l_alloc(void* ud, void* ptr, size_t osize, size_t nsize) {
      // Not used.
      (void)ud;
      (void)osize;
      if (nsize == 0) {
          free(ptr);
          return NULL;
      } else {
          return realloc(ptr, nsize);
      }
  }
#+end_src

** Calling Lua from C

#+begin_src c
  // === Lua Function Call ===
  //
  // a = f("how", t.x, 14)

  // === C Function Call ===

  // Function to be called.
  lua_getglobal(L, "f");
  // 1st argument.
  lua_pushliteral(L, "how");
  // Table to be indexed.
  lua_getglobal(L, "t");
  // Push the result of 2nd argument "t.x".
  lua_getfield(L, -1, "x");
  // Remove "t" from the stack.
  lua_remove(L, -2);
  // 3rd argument.
  lua_pushinteger(L, 14);
  // Call "f" with 3 arguments and return 1 result.
  // Pop "f" and its inputs. Push output from "f".
  lua_call(L, 3, 1);
  // Set output from "f" to global "a".
  lua_setglobal(L, "a");

  // === Definition: lua_call ===

  #define lua_call(L, n, r) lua_callk(L, (n), (r), 0, NULL)

  LUA_API void lua_callk(lua_State* L, int nargs, int nresults, lua_KContext ctx,
                         lua_KFunction k) {
      StkId func;
      lua_lock(L);
      api_check(L, k == NULL || !isLua(L->ci),
                "cannot use continuations inside hooks");
      // Ensure the stack has at least "n" elements.
      api_checknelems(L, nargs + 1);
      api_check(L, L->status == LUA_OK, "cannot do calls on non-normal thread");
      // Ensure function results do not overflow current stack size.
      checkresults(L, nargs, nresults);
      func = L->top.p - (nargs + 1);
      // Need to prepare continuation?
      if (k != NULL && yieldable(L)) {
          // Save continuation.
          L->ci->u.c.k = k;
          // Save context.
          L->ci->u.c.ctx = ctx;
          // Call function. Allow yields.
          luaD_call(L, func, nresults);
      } else {
          // Call function. Disallow yields.
          luaD_callnoyield(L, func, nresults);
      }
      // Adjust the callee's stack space to accomodate results.
      adjustresults(L, nresults);
      lua_unlock(L);
  }
#+end_src

** Lua Standalone Interpreter

#+begin_quote
  "To properly handle errors in our application code, we must call our code through Lua,
   so that it sets an appropriate context to catch errors — that is, it runs the code in
   the context of a ~setjmp~. In the same way that we can run Lua code in protected mode
   using ~pcall~, we can run C code using ~lua_pcall~. More specifically, we pack the code
   in a function and call that function through Lua, using ~lua_pcall~. With this setting,
   our C code will run in protected mode. Even in case of memory-allocation failure,
   ~lua_pcall~ returns a proper error code, leaving the interpreter in a consistent state.

   ...When we write library functions for Lua, however, usually they do not need to handle
   errors. Errors raised by a library function will be caught either by a ~pcall~ in Lua or
   by a ~lua_pcall~ in the application code. So, whenever a function in a C library detects
   an error, it can simply call ~lua_error~ (or better yet ~luaL_error~, which formats the error
   message and then calls ~lua_error~). The function ~lua_error~ tidies any loose ends in the
   Lua system and jumps back to the protected call that originated that execution, passing
   along the error message."

  - *Programming in Lua*, Roberto Ierusalimschy
#+end_quote

Lua is implemented not as a standalone program, but as a C library. The standalone Lua interpreter
is an interface that feeds files and strings from the user to the Lua library.

- *usage*: lua [options] [script [args]]

- *options*:
  
  - ~-e stat~: execute string ~stat~.
    
  - ~-i~: enter interactive mode after running script.
    
  - ~-l mod~: "require" ~mod~ and assign it to global ~mod~.
    
  - ~-l g=mod~: "require" ~mod~ and assign it to global ~g~.
    
  - ~-v~: print version information.
    
  - ~-E~: ignore environment variables.
    
  - ~-W~: turn warnings on.
    
  - ~--~: stop handling options.
    
  - ~-~: execute stdin as a file and stop handling options.

After handling its options, Lua runs the given script. When called without arguments, Lua behaves
as ~lua -v -i~ when the standard input is a terminal, and as ~lua -~ otherwise.

#+begin_src c
  // === Global Variables and Constants ===

  #define LUA_PROGNAME "lua"

  #define LUA_INIT_VAR "LUA_INIT"

  #define LUA_INITVARVERSION LUA_INIT_VAR LUA_VERSUFFIX

  // Holds a static, global reference to the current thread.
  static lua_State* globalL = NULL;

  static const char* progname = LUA_PROGNAME;

  // === Signal Interrupt ===

  #if defined(LUA_USE_POSIX)
  // Use 'sigaction' when available.
  static void setsignal(int sig, void (*handler)(int)) {
      struct sigaction sa;
      sa.sa_handler = handler;
      sa.sa_flags = 0;
      // Do not mask signal.
      sigemptyset(&sa.sa_mask);
      sigaction(sig, &sa, NULL);
  }
  #else

  #define setsignal signal

  #endif

  static void lstop(lua_State* L, lua_Debug* ar) {
      // Debug is an unused argument.
      (void)ar;
      // Reset hook.
      lua_sethook(L, NULL, 0, 0);
      luaL_error(L, "interrupted!");
  }

  // Because a signal interrupt cannot change a Lua state directly,
  // this function sets a hook, which, when called by the Lua
  // runtime, will stop the interpreter.
  static void laction(int i) {
      int flag = LUA_MASKCALL | LUA_MASKRET | LUA_MASKLINE | LUA_MASKCOUNT;
      // If another SIGINT happens, terminate process.
      setsignal(i, SIG_DFL);
      lua_sethook(globalL, lstop, flag, 1);
  }

  // === Error Messaging ===

  static void print_usage(const char* badoption) {
      lua_writestringerror("%s: ", progname);
      if (badoption[1] == 'e' || badoption[1] == 'l') {
          lua_writestringerror("'%s' needs argument\n", badoption);
      } else {
          lua_writestringerror("unrecognized option '%s'\n", badoption);
          lua_writestringerror(
              "usage: %s [options] [script [args]]\n"
              "Available options are:\n"
              "  -e stat   execute string 'stat'\n"
              "  -i        enter interactive mode after executing 'script'\n"
              "  -l mod    require library 'mod' into global 'mod'\n"
              "  -l g=mod  require library 'mod' into global 'g'\n"
              "  -v        show version information\n"
              "  -E        ignore environment variables\n"
              "  -W        turn warnings on\n"
              "  --        stop handling options\n"
              "  -         stop handling options and execute stdin\n",
              progname);
      }
  }

  // Print error message. Add program name if present.
  static void l_message(const char* pname, const char* msg) {
      if (pname) {
          lua_writestringerror("%s: ", pname);
      }
      lua_writestringerror("%s\n", msg);
  }

  // If error status, print error message on top of stack.
  static int report(lua_State* L, int status) {
      if (status != LUA_OK) {
          const char* msg = lua_tostring(L, -1);
          if (msg == NULL) {
              msg = "(error message not a string)";
          }
          l_message(progname, msg);
          lua_pop(L, 1);
      }
      return status;
  }

  // Prepare error messages on the stack.
  static int msghandler(lua_State* L) {
      const char* msg = lua_tostring(L, 1);
      // If error object is not a string, check for metamethod "__tostring".
      if (msg == NULL) {
          if (luaL_callmeta(L, 1, "__tostring") &&
              lua_type(L, -1) == LUA_TSTRING) {
              return 1;
          } else {
              msg = lua_pushfstring(L, "(error object is a %s value)",
                                    luaL_typename(L, 1));
          }
      }
      // Append a stack trace.
      luaL_traceback(L, L, msg, 1);
      return 1;
  }

  // === Chunk Evaluation ===

  // Interface to "lua_pcall": Sets both error-messaging and signal-interrupt function.
  // Runs protected function calls on chunks.
  static int docall(lua_State* L, int narg, int nres) {
      // Function call status.
      int status;
      // Function index.
      int base = lua_gettop(L) - narg;
      // Insert message handler under function and its arguments.
      lua_pushcfunction(L, msghandler);
      lua_insert(L, base);
      // Make Lua state available to "laction".
      globalL = L;
      // Set signal-interrupt handler to "laction".
      setsignal(SIGINT, laction);
      // Call the protected function.
      status = lua_pcall(L, narg, nres, base);
      // Reset signal-interrupt handler to default.
      setsignal(SIGINT, SIG_DFL);
      // Remove message handler from stack.
      lua_remove(L, base);
      return status;
  }

  static void print_version(void) {
      lua_writestring(LUA_COPYRIGHT, strlen(LUA_COPYRIGHT));
      lua_writeline();
  }

  // Store all the command line arguments in table "arg".
  static void createargtable(lua_State* L, char** argv, int argc, int script) {
      int i, narg;
      // Number of positive indices.
      narg = argc - (script + 1);
      lua_createtable(L, narg, script + 1);
      for (i = 0; i < argc; i++) {
          lua_pushstring(L, argv[i]);
          lua_rawseti(L, -2, i - script);
      }
      lua_setglobal(L, "arg");
  }

  // If a chunk compiles correctly, execute.
  static int dochunk(lua_State* L, int status) {
      if (status == LUA_OK) {
          status = docall(L, 0, 0);
      }
      return report(L, status);
  }

  static int dofile(lua_State* L, const char* name) {
      return dochunk(L, luaL_loadfile(L, name));
  }

  static int dostring(lua_State* L, const char* s, const char* name) {
      return dochunk(L, luaL_loadbuffer(L, s, strlen(s), name));
  }

  // Receive "globname[=modname]" and run "globname=require(modname)".
  // If no explicit modname and globname contains "-", cut suffix after
  // "-" to make the global name.
  static int dolibrary(lua_State* L, char* globname) {
      int status;
      char* suffix = NULL;
      char* modname = strchr(globname, '=');
      if (modname == NULL) {
          modname = globname;
          suffix = strchr(modname, *LUA_IGMARK);
      } else {
          // Global name ends here.
          *modname = '\0';
          // Module name starts here, after "=".
          modname++;
      }
      lua_getglobal(L, "require");
      lua_pushstring(L, modname);
      // Call "require(modname)".
      status = docall(L, 1, 1);
      if (status == LUA_OK) {
          // If suffix mark, remove it.
          if (suffix != NULL) {
              *suffix = '\0';
          }
          lua_setglobal(L, globname);
      }
      return report(L, status);
  }

  // Push arguments from "arg" table to the stack.
  static int pushargs(lua_State* L) {
      int i, n;
      if (lua_getglobal(L, "arg") != LUA_TTABLE) {
          luaL_error(L, "'arg' is not a table");
      }
      n = (int)luaL_len(L, -1);
      luaL_checkstack(L, n + 3, "too many arguments to script");
      for (i = 1; i <= n; i++) {
          lua_rawgeti(L, -i, i);
      }
      lua_remove(L, -i);
      return n;
  }

  // Push arguments to script and run.
  static int handle_script(lua_State* L, char** argv) {
      int status;
      const char* fname = argv[0];
      if (strcmp(fname, "-") == 0 && strcmp(argv[-1], "--") != 0) {
          // stdin
          fname = NULL;
      }
      status = luaL_loadfile(L, fname);
      if (status == LUA_OK) {
          int n = pushargs(L);
          status = docall(L, n, LUA_MULTRET);
      }
      return report(L, status);
  }

  // === Command-Line Flags ====

  // invalid flag
  #define has_error 1
  // interactive
  #define has_i     2
  // version
  #define has_v     4
  // environment: yes
  #define has_e     8
   // environment: no
  #define has_E    16

  // Parse command-line flags and compile into bitmask.
  static int collectargs(char** argv, int* first) {
      int args = 0;
      int i;
      // If program name is non-empty, save it.
      if (argv[0] != NULL) {
          if (argv[0][0]) {
              progname = argv[0];
          }
      } else {
          *first = -1;
          return 0;
      }
      // Handle command-line arguments.
      for (i = 1; argv[i] != NULL; i++) {
          *first = i;
          // If not a flag, stop handling options.
          if (argv[i][0] != '-') {
              return args;
          }
          // Parse flags.
          switch (argv[i][1]) {
              // "--""
              case '-': /* '--' */
                  if (argv[i][2] != '\0') {
                      return has_error;
                  }
                  // If there is a script name, it comes after "--".
                  *first = (argv[i + 1] != NULL) ? i + 1 : 0;
                  return args;
              // "-"
              case '\0':
                  return args;
              // "-E"
              case 'E':
                  if (argv[i][2] != '\0') {
                      return has_error;
                  }
                  args |= has_E;
                  break;
              // "-W"
              case 'W':
                  if (argv[i][2] != '\0') {
                      return has_error;
                  }
                  break;
              // "-i"
              case 'i':
                  args |= has_i;
              // Fallthrough: "-i" implies "-v".
              case 'v':
                  if (argv[i][2] != '\0') {
                      return has_error;
                  }
                  args |= has_v;
                  break;
              // "-e"
              case 'e':
                  args |= has_e;
              // Fallthrough to "-l".
              case 'l':
                  // If no concatenated argument, try next argument.
                  if (argv[i][2] == '\0') {
                      i++;
                      if (argv[i] == NULL || argv[i][0] == '-') {
                          return has_error;
                      }
                  }
                  break;
              // Invalid flag.
              default:
                  return has_error;
          }
      }
      // No script name.
      *first = 0;
      return args;
  }

  // Process "-e", "-l", and "-W" flags.
  static int runargs(lua_State* L, char** argv, int n) {
      int i;
      // By default, Lua standalone warnings are off.
      lua_warning(L, "@off", 0);
      for (i = 1; i < n; i++) {
          int option = argv[i][1];
          lua_assert(argv[i][0] == '-');
          switch (option) {
              case 'e':
              case 'l': {
                  int status;
                  char* extra = argv[i] + 2;
                  if (*extra == '\0') {
                      extra = argv[++i];
                  }
                  lua_assert(extra != NULL);
                  status = (option == 'e') ? dostring(L, extra, "=(command line)")
                                           : dolibrary(L, extra);
                  if (status != LUA_OK) {
                      return 0;
                  }
                  break;
              }
              case 'W':
                  lua_warning(L, "@on", 0);
                  break;
          }
      }
      return 1;
  }

  // If present, initialize environment variables.
  static int handle_luainit(lua_State* L) {
      const char* name = "=" LUA_INITVARVERSION;
      const char* init = getenv(name + 1);
      if (init == NULL) {
          name = "=" LUA_INIT_VAR;
          init = getenv(name + 1);
      }
      if (init == NULL) {
          return LUA_OK;
      } else if (init[0] == '@') {
          return dofile(L, init + 1);
      } else {
          return dostring(L, init, name);
      }
  }

  // === Read-Eval-Print Loop ===

  #define LUA_PROMPT  "> "
  #define LUA_PROMPT2 ">> "

  #define LUA_MAXINPUT 512

  // lua_stdin_is_tty(): Is Lua running interactively?
  #if !defined(lua_stdin_is_tty)

  #if defined(LUA_USE_POSIX)

  #include <unistd.h>
  #define lua_stdin_is_tty() isatty(0)

  #elif defined(LUA_USE_WINDOWS)

  #include <io.h>
  #include <windows.h>

  #define lua_stdin_is_tty() _isatty(_fileno(stdin))

  #else

  // ISO C definition: Assume stdin is tty.
  #define lua_stdin_is_tty() 1

  #endif

  #endif

  // Initialize readline system if configured.
  #if !defined(lua_readline)
  // Lua will be linked with "-lreadline".
  #if defined(LUA_USE_READLINE)

  #include <readline/history.h>
  #include <readline/readline.h>

  // The following functions should be provided if "lua_readline" is undefined.
  #define lua_initreadline(L)        ((void)L, rl_readline_name = "lua")
  #define lua_readline(buff, prompt) ((void)buff, readline(prompt))
  #define lua_saveline(line)         add_history(line)
  #define lua_freeline(line)         free(line)

  // Use dynamically-loaded readline or nothing.
  #else
  // Pointer to "readline" (if any).
  typedef char* (*l_readlineT)(const char* prompt);
  static l_readlineT l_readline = NULL;

  // Pointer to "add_history" (if any).
  typedef void (*l_addhistT)(const char* string);
  static l_addhistT l_addhist = NULL;

  static char* lua_readline(char* buff, const char* prompt) {
      if (l_readline != NULL) {
          return (*l_readline)(prompt);
      } else {
          // If "readline" unavailable, emulate over buffer.
          fputs(prompt, stdout);
          fflush(stdout);
          return fgets(buff, LUA_MAXINPUT, stdin);
      }
  }

  static void lua_saveline(const char* line) {
      if (l_addhist != NULL) {
          (*l_addhist)(line);
      }
  }

  static void lua_freeline(char* line) {
      // An emulated "readline" uses an automatic buffer.
      if (l_readline != NULL) {
          free(line);
      }
  }

  // Try to load "readline" dynamically.
  #if defined(LUA_USE_DLOPEN) && defined(LUA_READLINELIB)

  #include <dlfcn.h>

  static void lua_initreadline(lua_State* L) {
      void* lib = dlopen(LUA_READLINELIB, RTLD_NOW | RTLD_LOCAL);
      if (lib == NULL) {
          lua_warning(L, "library '" LUA_READLINELIB "' not found", 0);
      } else {
          const char** name = cast(const char**, dlsym(lib, "rl_readline_name"));
          if (name != NULL) {
              *name = "lua";
          }
          l_readline = cast(l_readlineT, cast_func(dlsym(lib, "readline")));
          l_addhist = cast(l_addhistT, cast_func(dlsym(lib, "add_history")));
          if (l_readline == NULL) {
              lua_warning(L, "unable to load 'readline'", 0);
          }
      }
  }

  #else

  #define lua_initreadline(L) ((void)L)

  #endif

  #endif

  #endif

  static const char* get_prompt(lua_State* L, int firstline) {
      if (lua_getglobal(L, firstline ? "_PROMPT" : "_PROMPT2") == LUA_TNIL) {
          return (firstline ? LUA_PROMPT : LUA_PROMPT2);
      } else {
          const char* p = luaL_tolstring(L, -1, NULL);
          lua_remove(L, -2);
          return p;
      }
  }

  // Mark in error messages for incomplete statements.
  #define EOFMARK "<eof>"
  #define marklen (sizeof(EOFMARK) / sizeof(char) - 1)

  // Check for syntax error: incomplete statement.
  static int incomplete(lua_State* L, int status) {
      if (status == LUA_ERRSYNTAX) {
          size_t lmsg;
          const char* msg = lua_tolstring(L, -1, &lmsg);
          if (lmsg >= marklen && strcmp(msg + lmsg - marklen, EOFMARK) == 0) {
              return 1;
          }
      }
      return 0;
  }

  // Prompt the user, read a line, and push it onto the stack.
  static int pushline(lua_State* L, int firstline) {
      char buffer[LUA_MAXINPUT];
      size_t l;
      const char* prmt = get_prompt(L, firstline);
      char* b = lua_readline(buffer, prmt);
      // Remove the prompt.
      lua_pop(L, 1);
      // No input.
      if (b == NULL) {
          return 0;
      }
      l = strlen(b);
      // Remove newline if present.
      if (l > 0 && b[l - 1] == '\n') {
          b[--l] = '\0';
      }
      lua_pushlstring(L, b, l);
      lua_freeline(b);
      return 1;
  }

  // Try to compile line on stack as "return <line>".
  static int addreturn(lua_State* L) {
      // Original line
      const char* line = lua_tostring(L, -1);
      const char* retline = lua_pushfstring(L, "return %s;", line);
      int status = luaL_loadbuffer(L, retline, strlen(retline), "=stdin");
      if (status == LUA_OK) {
          lua_remove(L, -2);
      } else {
          lua_pop(L, 2);
      }
      return status;
  }

  // If local variables are present in interactive mode, set warning.
  static void checklocal(const char* line) {
      static const size_t szloc = sizeof("local") - 1;
      static const char space[] = " \t";
      // Skip spaces.
      line += strspn(line, space);
      // "local" followed by spaces.
      if (strncmp(line, "local", szloc) == 0 &&
          strchr(space, *(line + szloc)) != NULL) {
          lua_writestringerror(
              "%s\n",
              "warning: locals do not survive across lines in interactive mode");
      }
  }

  // Read multiple lines until a complete Lua statement.
  static int multiline(lua_State* L) {
      size_t len;
      // Get first line.
      const char* line = lua_tolstring(L, 1, &len); /* get first line */
      checklocal(line);
      // Repeat until a complete statement or syntax error.
      for (;;) {
          int status = luaL_loadbuffer(L, line, len, "=stdin");
          if (!incomplete(L, status) || !pushline(L, 0)) {
              return status;
          }
          // Remove error message from incomplete line.
          lua_remove(L, -2);
          // Add newline between two lines and join them.
          lua_pushliteral(L, "\n");
          lua_insert(L, -2);
          lua_concat(L, 3);
          line = lua_tolstring(L, 1, &len);
      }
  }

  // Read line and try to compile as a "return" expression. If failure,
  // then try to compile as a statement.
  static int loadline(lua_State* L) {
      const char* line;
      int status;
      lua_settop(L, 0);
      // No input.
      if (!pushline(L, 1)) {
          return -1;
      }
      // Not an expression.
      if ((status = addreturn(L)) != LUA_OK) {
          status = multiline(L);
      }
      line = lua_tostring(L, 1);
      // If non-empty line, save history.
      if (line[0] != '\0') {
          lua_saveline(line);
      }
      // Remove line from stack.
      lua_remove(L, 1);
      lua_assert(lua_gettop(L) == 1);
      return status;
  }

  // Use Lua's print function to display values on stack.
  static void l_print(lua_State* L) {
      int n = lua_gettop(L);
      if (n > 0) {
          luaL_checkstack(L, LUA_MINSTACK, "too many results to print");
          lua_getglobal(L, "print");
          lua_insert(L, 1);
          if (lua_pcall(L, n, 0, 0) != LUA_OK) {
              l_message(progname, lua_pushfstring(L, "error calling 'print' (%s)",
                                                  lua_tostring(L, -1)));
          }
      }
  }

  static void doREPL(lua_State* L) {
      int status;
      const char* oldprogname = progname;
      // Omit program name for errors in interactive mode.
      progname = NULL;
      // Initializes the readline system if available.
      lua_initreadline(L);
      // While there is input from the terminal, parse, compile, evaluate, and print.
      while ((status = loadline(L)) != -1) {
          if (status == LUA_OK) {
              // Evaluate.
              status = docall(L, 0, LUA_MULTRET);
          }
          // Success: Print contents of stack.
          if (status == LUA_OK) {
              l_print(L);
          } else {
              // Failure: Print error message on top of stack.
              report(L, status);
          }
      }
      // Clear stack.
      lua_settop(L, 0);
      // Insert a newline.
      lua_writeline();
      // Reset program name.
      progname = oldprogname;
  }

  // === Lua Libraries ===

  #define luai_openlibs(L) luaL_openselectedlibs(L, ~0, 0)

  // === Lua Stand-Alone Interpreter ===

  // Main body of the Lua stand-alone intepreter. Called in protected mode.
  // Parses and handles all arguments to the main program.
  static int pmain(lua_State* L) {
      int argc = (int)lua_tointeger(L, 1);
      char** argv = (char**)lua_touserdata(L, 2);
      // error = argument index | no name = -1 | no script name = 0 | script name = index
      int script;
      // Traverses all arguments from "argv" and returns a mask of those
      // arguments before running any Lua code. Returns an error code if it
      // finds any invalid arguments.
      int args = collectargs(argv, &script);
      // First argument is not an option.
      int optlim = (script > 0) ? script : argc;
      // Check whether the program and the Lua library being called
      // are using the same version of Lua and the same numeric types.
      luaL_checkversion(L);
      // If "collectargs" returns an error code, print usage information
      // along with the incorrect argument.
      if (args == has_error) {
          print_usage(argv[script]);
          return 0;
      }
      // If option -v, print Lua version.
      if (args & has_v) {
          print_version();
      }
      // If option -E, signal for libraries to ignore environment variables.
      if (args & has_E) {
          lua_pushboolean(L, 1);
          lua_setfield(L, LUA_REGISTRYINDEX, "LUA_NOENV");
      }
      // Open standard libraries.
      luai_openlibs(L);
      // Create a table of command-line arguments.
      createargtable(L, argv, argc, script);
      // Start garbage collector in generational mode.
      lua_gc(L, LUA_GCRESTART);
      lua_gc(L, LUA_GCGEN);
      // If not option -E, run LUA_INIT.
      if (!(args & has_E)) {
          if (handle_luainit(L) != LUA_OK) {
              return 0;
          }
      }
      // Execute arguments -e, -l, and -W.
      if (!runargs(L, argv, optlim)) {
          return 0;
      }
      // Execute main script (if there is one).
      if (script > 0) {
          if (handle_script(L, argv + script) != LUA_OK) {
              return 0;
          }
      }
      // If -i option, run read-eval-print loop.
      if (args & has_i) {
          doREPL(L);
      }
      // If no active option and output is a terminal,
      // print version and run read-eval-print loop.
      else if (script < 1 && !(args & (has_e | has_v))) {
          if (lua_stdin_is_tty()) {
              print_version();
              doREPL(L);
          } else {
              // Execute stdin as file.
              dofile(L, NULL);
          }
      }
      // Signal no errors.
      lua_pushboolean(L, 1);
      return 1;
  }

  // The requisite main program as implemented for the Lua stand-alone interpreter.
  int main(int argc, char* argv[]) {
      int status, result;
      // Open Lua state.
      lua_State* L = luaL_newstate();
      if (L == NULL) {
          l_message(argv[0], "cannot create state: not enough memory");
          return EXIT_FAILURE;
      }
      // Stop garbage collection while building state
      lua_gc(L, LUA_GCSTOP);
      // Prepare call to 'pmain' in protected mode.
      lua_pushcfunction(L, &pmain);
      // 1st argument as integer.
      lua_pushinteger(L, argc);
      // 2nd argument userdata.
      lua_pushlightuserdata(L, argv);
      // Call "pmain".
      status = lua_pcall(L, 2, 1, 0);
      // Get result.
      result = lua_toboolean(L, -1);
      // Check status. If error message on top of stack,
      // print to stderror.
      report(L, status);
      // Close Lua state.
      lua_close(L);
      return (result && status == LUA_OK) ? EXIT_SUCCESS : EXIT_FAILURE;
  }
#+end_src

** Lua C Map Function

For C functions registered in Lua's virtual machine, arguments must be passed through
the stack, not as arguments to the function. A C function receives its arguments
from the stack in direct order, where the first index corresponds to the function's
first argument. To return values to Lua, a C function pushes its results onto the
stack, also in direct order, and returns in C the number of results.

- ~lua_CFunction~ :: ~typedef int (*lua_CFunction) (lua_State *L)~

#+begin_src c
  // === C API ===

  #include "lauxlib.h"
  #include "lua.h"

  lua_State* L = luaL_newstate();
  luaL_openlibs(L);

  int f_map(lua_State* L) {
      int i, n;

      // 1st argument must be a table (t).
      luaL_checktype(L, 1, LUA_TTABLE);

      // 2nd argument must be a function (f).
      luaL_checktype(L, 2, LUA_TFUNCTION);

      // Get size of table
      n = luaL_len(L, 1);

      for (i = 1; i <= n; i += 1) {
          // Push f
          lua_pushvalue(L, 2);
          // Push t[i]
          lua_geti(L, 1, i);
          // Call f(t[i])
          lua_call(L, 1, 1);
          // t[i] = result
          lua_seti(L, 1, i);
      }
      // Number of results left on the stack.
      return 0;
  }

  lua_pushfunction(L, f_map);
  lua_setglobal(L, "map");

  // === Lua ===
  //
  // array = { 1, 2, 3, 4 }
  // map(array, function (x) return x * x end)
  // array --> { 1, 4, 9, 16 }
#+end_src

** Lua C String Function

#+begin_src c
  // === C API ===

  #include <ctype.h>

  #include "lauxlib.h"
  #include "lua.h"

  lua_State* L = luaL_newstate();
  luaL_openlibs(L);

  // Uppercase a string, using a buffer.
  static int f_uppercase(lua_State* L) {
      size_t l;
      size_t i;
      // Declare a buffer.
      luaL_Buffer b;

      // Ensure argument is a string.
      const char* s = luaL_checklstring(L, 1, &l);

      // Initialize buffer.
      char* p = luaL_buffinitsize(L, &b, l);

      // For each character in the buffer, uppercase that character.
      for (i = 0; i < l; i += 1) {
          p[i] = toupper(uchar(s[i]));
      }

      // Flush buffer. Leave resulting string on the stack.
      luaL_pushresultsize(&b, l);

      // Number of results left on the stack.
      return 1;
  }

  lua_pushfunction(L, f_uppercase);
  lua_setglobal(L, "uppercase");

  // === Lua ===
  //
  // uppercase("abc") -->  "ABC"
#+end_src

Lua's generic buffer implementation (5.5):

#+begin_src c
  // LUAI_MAXALIGN defines fields that, when used in a union, ensure
  // maximum alignment for the other items in that union.
  //
  // LUAI_MAXALIGN -> lua_Number n; double u; void *s; lua_Integer i; long l

  struct luaL_Buffer {
      char* b;      // Buffer address
      size_t size;  // Buffer size
      size_t n;     // Number of characters in buffer
      lua_State* L;
      union {
          LUAI_MAXALIGN;            // Ensure maximum alignment for buffer
          char b[LUAL_BUFFERSIZE];  // Initial buffer
      } init;
  };
#+end_src

A string buffer allows C code to build Lua strings piecemeal:

- Declare a variable ~b~ of type ~luaL_Buffer~.

- Initialize with ~luaL_buffinit(L, &b)~.

- Then add string pieces to buffer, using any of the ~luaL_add~ functions.

- Finish by calling ~luaL_pushresult(&b)~, which leaves the final string
  on top of the stack.

** Lua C Bit Array

The Lua type ~userdata~ allows the creation of C data structures within the Lua environment.
~userdata~ contain memory blocks managed by the Lua VM, which are transparently accessible
to C code but are opaque objects when accessed by Lua.

Lua's only predefined operations for ~userdata~ are assignment and identity testing.
Metatables provide user-defined operations.

#+begin_src c
  #include <limits.h>
  #include <stddef.h>

  #include "lauxlib.h"
  #include "lua.h"

  // Boolean arrays where each entry is stored in a single bit.

  // Number of bits in an unsigned integer.
  #define BITS_PER_WORD (CHAR_BIT * sizeof(unsigned int))
  // Word that stores bit that corresponds to a given index.
  #define I_WORD(i) ((unsigned int)(i) / BITS_PER_WORD)
  // Mask to access the correct bit inside the word.
  #define I_BIT(i) (1 << ((unsigned int)(i) % BITS_PER_WORD))

  #define checkarray(L) (BitArray*)luaL_checkudata(L, 1, "LuaBook.array")

  typedef struct BitArray {
      int size;
      // Variable part. "values[1]" is a placeholder. This is the C89 idiom
      // for declaring variable-sized arrays inside structs. C99 would declare
      // "values[]" instead. This syntax is called the "flexible array member".
      unsigned int values[1];
  } BitArray;

  static int newarray(lua_State* L) {
      int i;
      size_t nbytes;
      BitArray* a;

      // Number of bits
      int n = (int)luaL_checkinteger(L, 1);
      luaL_argcheck(L, n >= 1, 1, "invalid size");
      // The size of an array with "n" elements. Subtracts one from "n"
      // because the original structure already includes space for one
      // element.
      nbytes = sizeof(BitArray) + I_WORD(n - 1) * sizeof(unsigned int);
      a = (BitArray*)lua_newuserdata(L, nbytes);

      a->size = n;
      for (i = 0; i <= I_WORD(n - 1); i++) {
          // Initialize array.
          a->values[i] = 0;
      }

      luaL_getmetatable(L, "LuaBook.array");
      lua_setmetatable(L, -2);

      // New userdata is already on the stack.
      return 1;
  }

  static int getsize(lua_State* L) {
      BitArray* a = checkarray(L);
      lua_pushinteger(L, a->size);
      return 1;
  }

  static unsigned int* getparams(lua_State* L, unsigned int* mask) {
      BitArray* a = checkarray(L);
      int index = (int)luaL_checkinteger(L, 2) - 1;

      luaL_argcheck(L, 0 <= index && index < a->size, 2, "index out of range");

      // Mask to access correct bit.
      *mask = I_BIT(index);
      // Word address.
      return &a->values[I_WORD(index)];
  }

  static int setarray(lua_State* L) {
      unsigned int mask;
      unsigned int* entry = getparams(L, &mask);
      luaL_checkany(L, 3);
      if (lua_toboolean(L, 3)) {
          *entry |= mask;
      } else {
          *entry &= ~mask;
      }
      return 0;
  }

  static int getarray(lua_State* L) {
      unsigned int mask;
      unsigned int* entry = getparams(L, &mask);
      lua_pushboolean(L, *entry & mask);
      return 1;
  }

  int array2string(lua_State* L) {
      BitArray* a = checkarray(L);
      lua_pushfstring(L, "array(%d)", a->size);
      return 1;
  }

  static const struct luaL_Reg arraylib_f[] = {
      { "new", newarray },
      { NULL,  NULL }
  };

  static const struct luaL_Reg arraylib_m[] = {
      { "__newindex", setarray },
      { "__index",    getarray },
      { "__len",      getsize },
      { "__tostring", array2string },
      { NULL,         NULL }
  };

  // "luaopen_<module name>" is a naming convention used by "require"
  // to find loaders for C libraries.
  int luaopen_array(lua_State* L) {
      // Creates a metatable registered with "LuaBook.array".
      luaL_newmetatable(L, "LuaBook.array");
      // Registers functions with table on top of stack. In this case, a
      // metatable.
      luaL_setfuncs(L, arraylib_m, 0);
      // Creates a new table and registers functions from the provided list.
      // Implemented as the macro "(luaL_newlibtable(L, 1), luaL_setfuncs(L, l,
      // 0))".
      luaL_newlib(L, arraylib_f);
      return 1;
  }
#+end_src

** Lua C Directory Iterator

#+begin_src c
  // === Lua Iterator ==
  //
  // for fname in dir.open(".") do
  //     print(fname)
  // end

  // === C Implmentation ===

  #include <dirent.h>
  #include <errno.h>
  #include <string.h>

  #include "lauxlib.h"
  #include "lua.h"

  // Forward declaration for the iterator function.
  static int dir_iter(lua_State* L);

  static int lua_dir(lua_State* L) {
      const char* path = luaL_checkstring(L, 1);

      // Create a userdata to store a DIR address.
      DIR** d = (DIR**)lua_newuserdata(L, sizeof(DIR*));

      // Pre-initialize
      *d = NULL;

      // Set its metatable.
      luaL_getmetatable(L, "LuaBook.dir");
      lua_setmetatable(L, -2);

      // Try to open the given directory.
      *d = opendir(path);
      // Error opening the directory?
      if (*d == NULL) {
          luaL_error(L, "cannot open %s: %s", path, strerror(errno));
      }
      // Creates and returns the iterator function. Its sole upvalue,
      // the directory userdata, is already on the top of the stack.
      lua_pushcclosure(L, dir_iter, 1);
      return 1;
  }

  // Iterator.
  static int dir_iter(lua_State* L) {
      DIR* d = *(DIR**)lua_touserdata(L, lua_upvalueindex(1));
      struct dirent* entry = readdir(d);
      if (entry != NULL) {
          lua_pushstring(L, entry->d_name);
          return 1;
      } else {
          // No more values to return.
          return 0;
      }
  }

  // Garbage collection metamethod.
  static int dir_gc(lua_State* L) {
      DIR* d = *(DIR**)lua_touserdata(L, 1);
      if (d) {
          closedir(d);
      }
      return 0;
  }

  // Add function to registry.
  static const struct luaL_Reg dirlib[] = {
      { "open", lua_dir },
      { NULL,   NULL }
  };

  // Open one-function library.
  int luaopen_dir(lua_State* L) {
      luaL_newmetatable(L, "LuaBook.dir");

      // Set its __gc field.
      lua_pushcfunction(L, dir_gc);
      lua_setfield(L, -2, "__gc");

      // Create the library.
      luaL_newlib(L, dirlib);
      return 1;
  }
#+end_src
