* Lua's Virtual Machine

** Sources

| source                          | author                                                                       |
|---------------------------------+------------------------------------------------------------------------------|
| *The Implementation of Lua 5.0* | Roberto Ierusalimschy, Luiz Henrique de Figueiredo, and Waldemar Celes Filho |
| *Crafting Interpreters*         | Robert Nystrom                                                               |

There are 35 instructions in Lua's virtual machine. Most instructions correspond
directly to language constructs, such as arithmetic, table creation and indexing,
function and method calls, setting variables and getting values. There are also jump
instructions for implementing control flow.

** Notational Conventions

- ~R(X)~: ~Xth~ register.
- ~K(X)~: ~Xth~ constant.
- ~RK(X)~: either ~R(X)~ or ~K(X-k)~, where ~R(X)~ is for values of ~X~ smaller
   than ~k~.
- ~G[X]~: field ~X~ in a table of globals.
- ~U[X]~: the ~Xth~ upvalue.
- ~Bx~ and ~sBx~: unsigned and signed 18-bit value.

** Op Code Instruction Set

#+begin_example
  MOVE      A B      R(A) := R(B)
  LOADK     A Bx     R(A) := K(Bx)
  LOADBOOL  A B C    R(A) := (Bool)B; if (C) PC++
  LOADNIL   A B      R(A) := ... := R(B) := nil
  GETUPVAL  A B      R(A) := U[B]
  GETGLOBAL A Bx     R(A) := G[K(Bx)]
  GETTABLE  A B C    R(A) := R(B)[RK(C)]
  SETGLOBAL A Bx     G[K(Bx)] := R(A)
  SETUPVAL  A B      U[B] := R(A)
  SETTABLE  A B C    R(A)[RK(B)] := RK(C)
  NEWTABLE  A B C    R(A) := {} (size = B,C)
  SELF      A B C    R(A+1) := R(B); R(A) := R(B)[RK(C)]
  ADD       A B C    R(A) := RK(B) + RK(C)
  SUB       A B C    R(A) := RK(B) - RK(C)
  MUL       A B C    R(A) := RK(B) * RK(C)
  DIV       A B C    R(A) := RK(B) / RK(C)
  POW       A B C    R(A) := RK(B) ^ RK(C)
  UNM       A B      R(A) := -R(B)
  NOT       A B      R(A) := not R(B)
  CONCAT    A B C    R(A) := R(B) .. ... .. R(C)
  JMP       sBx      PC += sBx
  EQ        A B C    if ((RK(B) == RK(C)) ~= A) then PC++
  LT        A B C    if ((RK(B) < RK(C)) ~= A) then PC++
  LE        A B C    if ((RK(B) <= RK(C)) ~= A) then PC++
  TEST      A B C    if (R(B) <=> C) then R(A) := R(B) else PC++
  CALL      A B C    R(A), ... ,R(A+C-2) := R(A)(R(A+1), ... ,R(A+B-1))
  TAILCALL  A B C    return R(A)(R(A+1), ... ,R(A+B-1))
  RETURN    A B      return R(A), ... ,R(A+B-2)
  FORLOOP   A sBx    R(A)+=R(A+2); if R(A) <?= R(A+1) then PC+= sBx
  TFORLOOP  A C      R(A+2), ... ,R(A+2+C) := R(A)(R(A+1), R(A+2));
  TFORPREP  A sBx    if type(R(A)) == table then R(A+1) := R(A), R(A):=next;
  SETLIST   A Bx     R(A)[Bx-Bx%FPF+i] := R(A+i), 1 <= i <= Bx%FPF+1
  SETLISTO  A Bx
  CLOSE     A        close stack variables up to R(A)
  CLOSURE   A Bx     R(A) := closure(KPROTO[Bx], R(A), ... ,R(A+n))
#+end_example

** Instruction Layout

Lua's virtual machine instructions take 32 bits divided into 3 or 4 fields.
The 6-bit ~OP~ field identifies the instruction. 8-bit field ~A~ is always
present. Fields ~B~ and ~C~ are 9 bits each. They can be combined into an
18-bit field: ~Bx~ (unsigned) and ~sBx~ (signed).

Most instructions use a three-address format, where ~A~ points to the register that
will hold the result and ~B~ and ~C~ point to the operands, which can be either a
register or a constant.

#+begin_example
  +----+---+-------+
  | OP | A | B | C |
  |----|---|-------|
  | OP | A | Bx    |
  |----|---|-------|
  | OP | A | sBx   |
  +----+---+-------+
#+end_example

** Lua Function to Bytecode

#+begin_src lua
  -- === Lua Function ===
  
  function max(a, b)
      local m = a
      if b > a then
          m = b
      end
      return m
  end

  -- === Bytecode ===
  --
  -- 1 MOVE      2 0 0    ; R(2) = R(0)
  -- 2 LT        0 0 1    ; R(0) < R(1) ?
  -- 3 JMP       1        ; to 5 (4+1)
  -- 4 MOVE      2 1 0    ; R(2) = R(1)
  -- 5 RETURN    2 2 0    ; return R(2)
  -- 6 RETURN    0 1 0    ; return
#+end_src


** Lua Data Types

#+begin_src c
  // tagged union (t, v)
  // where t = integer tag identifying type
  //       v = union of C types implementing Lua types
  typedef struct {
    int t;
    Value v;
  } TObject;

  typedef union {
    GCObject *gc; // strings, tables, functions (referenced and garbage-collected data)
    void *p;      // light user data
    lua_Number n; // numbers (Double by default)
    int b;        // booleans
  } Value;
#+end_src

** Register Based (Lua 5.0)

#+begin_src lua
  local a, t, i  -- 1: LOADNIL  0 2 0
  a = a + i      -- 2: ADD      0 0 2
  a = a + 1      -- 3: ADD      0 0 250 ; 1
  a = t[i]       -- 4: GETTABLE 0 1 2
#+end_src

** Stack Based (Lua 4.0)

#+begin_src lua
  local a, t, i   --  1: PUSHNIL    3
  a = a + i       --  2: GETLOCAL   0 ; a
                  --  3: GETLOCAL   2 ; i
                  --  4: ADD
                  --  5: SETLOCAL   0 ; a
  a = a + 1       --  6: GETLOCAL   0 ; a
                  --  7: ADDI       1
                  --  8: SETLOCAL   0 ; a
  a = t[i]        --  9: GETLOCAL   1 ; t
                  -- 10: GETINDEXED 2 ; i
                  -- 11: SETLOCAL   0 ; a
#+end_src

** Closures and UpValues

#+begin_example
  === Closures Implemented as UpValues ===

  1. Resolves local variables that are declared in surrounding functions.
  2. Capture variables that have already left the stack.

                               Function
                              +-----------+
             Closure      +-->| chunk     |--> bytecode
            +----------+  |   |-----------|
        +-->| function |--+   | constants |--> value array
        |   |----------|      +-----------+
        |   | upvalues |--+
        |   +----------+  |    UpValue Array     Upvalue
        |                 |   +-------------+   +----------+
        |                 +-->| 0           |-->| location |--+
        |                     +-------------+   +----------+  |
    +---|-----------------------------------------------------+
    V   |
  +---+----+---+-->
  | x | fn | y |
  +---+----+---+-->

  === Closing UpValues ===

                    Open UpValues --+
                                    |
                                    V
       Upvalue       Upvalue        Upvalue
     +----------+   +----------+   +----------+
     | next     |<--| next     |<--| next     |
     |----------|   |----------|   |----------|
   +-| location | +-| location | +-| location |
   | +----------+ | +----------+ | +----------+
   +---+          |              |
       |        +-+      +-------+
       V        V        V
     +---+----+---+----+---+----+
     | x | fn | y | fn | z | fn | <-- stack
     +---+----+---+----+---+----+

    Open Upvalue       Closed Upvalue
   +----------+       +----------+
   | next     |       | next     |
   |----------|       |----------|
   | closed   |       | closed z |<-+
   |----------|       |----------|  |
   | location |--+    | location |--+
   +----------+  |    +----------+
             +---+
    Stack    V        Stack
   +---+---+---+      +---+---+
   | x | y | z |      | x | y |
   +---+---+---+      +---+---+
#+end_example
