* Tables

** Sources

| source                                  | author                                                                 |
|-----------------------------------------+------------------------------------------------------------------------|
| *A Look at the Design of Lua*           | Roberto Ierusalimschy, Luiz Henrique De Figueiredo, and Waldemar Celes |
| *Programming in Lua*                    | Roberto Ierusalimschy                                                  |
| *Lua: An Extensible Extension Language* | Roberto Ierusalimschy, Luiz Henrique De Figueiredo, and Waldemar Celes |
| *The Implementation of Lua 5.0*         | Roberto Ierusalimschy, Luiz Henrique De Figueiredo, and Waldemar Celes |

** Definition

#+begin_quote
  "Lua combines procedural features with powerful data description facilities,
   by using a simple, yet powerful, mechanism of tables. This mechanism implements
   the concepts of records, arrays, and recursive data types (pointers), and adds
   some object-oriented facilities, such as methods with dynamic dispatching.
   Lua presents a mechanism of fallbacks that allows programmers to extend the
   semantics of the language in some unconventional ways."

  — *Lua: An Extensible Extension Language*, by Roberto Ierusalimschy,
    Luiz Henrique De Figueiredo, and Waldemar Celes

  "...[T]ables are implemented as hybrid data structures: they contain a hash part
   and an array part...This division is made only at a low implementation level;
   access to table fields is transparent, even to the virtual machine. Tables
   automatically and dynamically adapt their two parts according to their contents:
   the array part tries to store the values corresponding to integer keys from 1
   to some limit n. Values corresponding to non-integer keys or to integer keys
   outside the array range are stored in the hash part."

  — *The Implementation of Lua 5.0*, by Roberto Ierusalimschy,
    Luiz Henrique De Figueiredo, and Waldemar Celes
#+end_quote

** Implementation

Pulled from ~lobject.h~ of Lua 5.5, many of these examples are simplified and renamed for clarity.

#+begin_src c
  /* Side Note: "lu_byte" alias for "unsigned char" */

  /* === Lua Value === */
  typedef union Value {
      /* Garbage Collectable Objects */
      struct GCObject *gc;
      /* Light Userdata */
      void *p;
      /* Light C Functions */
      lua_CFunction f;
      /* Integers */
      lua_Integer i;
      /* Floats */
      lua_Number n;
      /* Type may suppress warnings for uninitialized values. */
      lu_byte ub;
  } Value;

  typedef struct TValue {
      /* One of five Lua values. */
      Value value_;
      /* Type Tag */
      lu_byte tt_;
  } TValue;

  /*
    Nodes for Hash tables: A pack of key-value pairs plus a "next"
    field to link colliding entries. The distribution of the key's
    fields ("key_tt" and "key_val") not forming a proper "TValue"
    allows for a smaller size for "Node" both in 4-byte and 8-byte
    alignments.
  */
  typedef union Node {
      struct NodeKey {
          /* One of five Lua values. */
          Value value_;
          /* Value Type Tag */
          lu_byte tt_;
          /* Key Type Tag */
          lu_byte key_tt;
          /* Chained Entries */
          int next;
          /* Key Value */
          Value key_val;
      } u;
      /* Direct access to node's value as a proper "TValue" */
      TValue i_val;
  } Node;

  /* === Lua Table === */
  typedef struct Table {
      /* CommonHeader */
      struct GCObject *next;
      lu_byte tt;
      lu_byte marked;
      /* 1 << p means tagmethod(p) is not present. */
      lu_byte flags;
      /* log2 size of "node" array. */
      lu_byte lsizenode;
      /* Number of slots in array. */
      unsigned int asize;
      /* Pointer to array. */
      TValue *array;
      /* Pointer to hashtable node. */
      Node *node;
      /* Pointer to table's metatable. */
      struct Table *metatable;
      GCObject *gclist;
  } Table;
#+end_src

** Implementing Modules

Lua encloses a chunk within the body of an anonymous function. A module is a populated table returned
by this anonymous function. Lexical scoping ensures only code within this table can access data within
the lexical environment of its parent function. 

*** Tables

#+begin_src lua
  -- === File: "chunk.lua" ===

  -- return function (...)
       local Module = {}

       function Module.new (x, y)
         return { ["x"] = x, ["y"] = y }
       end

       function Module.add (v1, v2)
         return Module.new(v1.x + v2.x, v1.y + v2.y)
       end

       function Module.magnitude (v)
         return math.sqrt(v.x ^ 2 + v.y ^ 2)
       end

       return Module
  -- end

  -- local vec = require("chunk")
  --
  -- five = vec.magnitude(vec.new(3, 4))
#+end_src

*** The ~_ENV~ Table

The anonymous function of each chunk is compiled in the scope of the local variable
~_ENV~, so that ~add~ compiles to ~_ENV.add~. By default, ~_ENV~ is loaded with a
fixed table called the global environment. Changing ~_ENV~ allows functions to be
called with different environments.

#+begin_src lua
  -- local _ENV = the global environment
  -- return function (...)
       local sqrt = math.sqrt
       local _ENV = {}

       -- _ENV["new"]
       function new (x, y)
         return { ["x"] = x, ["y"] = y }
       end
       -- _ENV["add"]
       function add (v1, v2)
         return new(v1.x + v2.x, v1.y + v2.y)
       end

       -- _ENV["magnitude"]
       function magnitude (v)
         return sqrt(v.x ^ 2 + v.y ^ 2)
       end

       return _ENV
  -- end
#+end_src

** Implementing Object-Oriented Programming

#+begin_quote
  "A table in Lua is an object in more than one sense. Like objects, tables have a state.
   Like objects, tables have an identity (a *self*) that is independent of their values;
   specifically, two objects (*tables*) with the same value are different objects, whereas
   an object can have different values at different times. Like objects, tables have a
   life cycle that is independent of who created them or where they were created."

  — Roberto Ierusalimschy
#+end_quote

*** Meta Tables

#+begin_quote

  "Metatables allow us to change the behavior of a value when confronted with an unknown operation.
   For instance, using metatables, we can define how Lua computes the expression ~a + b~, where
   ~a~ and ~b~ are tables. Whenever Lua tries to add two tables, it checks whether either of them
   has a metatable and whether this metatable has an ~__add~ field. If Lua finds this field, it
   calls the corresponding value — the so-called metamethod, which should be a function —
   to compute the sum."

  "Each value in Lua can have a metatable. Tables and userdata have individual metatables; values
   of other types share one single metatable for all values of that type. Lua always creates new
   tables without metatables...We can use ~setmetatable~ to set or change the metatable of a table"

  — *Programming in Lua*, Roberto Ierusalimschy
#+end_quote

#+begin_src lua
  local meta = {}

  function vector (x, y)
    local v = { ["x"] = x, ["y"] = y }
    setmetatable(v, meta)
    return v
  end

  -- Operator overloading through metamethods.
  function meta.__add (v1, v2)
    return vector(v1.x + v2.x, v1.y + v2.y)
  end

  A = vector(1, 2)
  B = vector(2, 2)
  C = A + B --> { x = 3, y = 4 }
#+end_src

#+begin_quote
  "When looking for a metamethod, Lua performs the following steps: if the first value has
   a metatable with the required metamethod, Lua uses this metamethod, independently of
   the second value; otherwise, if the second value has a metatable with the required
   metamethod, Lua uses it; otherwise, Lua raises an error."

  — *A Look at the Design of Lua*, Roberto Ierusalimschy, Luiz Henrique De Figueiredo, and Waldemar Celes
#+end_quote

*** Protoypes

#+begin_src lua
  -- Prototype
  local Account = { balance = 0 }

  -- Delegating the indexing operator "[]".
  -- If we access an absent field, Lua will look for a
  -- corresponding field in the table's metatable.
  local meta = { __index = Account }
  --    meta = { __index = function (self, key) return Account[key] end }

  --       Account.new = function (self)
  function Account:new ()
    local object = {}
    setmetatable(object, meta)
    return object
  end

  -- Remove indirection by setting "Account"
  -- to new object's metatable directly.
  function Account:new ()
    local object = {}
    self.__index = self
    setmetatable(object, self)
    return object
  end

  --       Account.deposit = function (self, v)
  function Account:deposit (v)
    self.balance = self.balance + v
  end

  --       Account.withdraw = function (self, v)
  function Account:withdraw (v)
    if amount > self.balance then error("insufficient funds") end
    self.balance = self.balance - v
  end

  --       Account.balance = function (self)
  function Account:balance ()
    return self.balance
  end

  return Account

  -- === In Another File ===
  Account = require("Account")

  account = Account:new()
  -- equivalent ->
  account = Account.new(Account)

  account:deposit(100)
  -- equivalent ->
  Account.deposit(account, 100)

  balance = account:balance()
  -- equivalent ->
  balance = Account.balance(account)
#+end_src

*** Privacy

**** Read-Only Tables

#+begin_src lua
  function freeze (t)
    local proxy = {}
    local meta = {
      ["__index"] = t,
      -- Ignore key-value assignments.
      ["__newindex"] = function (t, k, v)
        return t
      end
    }
    setmetatable(proxy, meta)
    return proxy
  end
#+end_src

**** Account Revisited

#+begin_src lua
  -- === Implementation 1: state and interface ===

  function new_account (x)
    -- === private state table ===
    local state = { balance = x }

    local deposit = function (v)
                      state.balance = state.balance + v
                    end

    local withdraw = function (v)
                       if amount > state.balance then error("insufficient funds") end
                       state.balance = state.balance - v
                     end

    local get_balance = function () return state.balance end

    -- === public interface table ===
    return {
      ["withdraw"]    = withdraw,
      ["deposit"]     = deposit,
      ["get_balance"] = get_balance
    }
  end

  -- === Implementation 2: weak key locks ===

  local balance = {}

  -- Set keys to weak for garbage collection.
  setmetatable(balance, { __mode = "k" })

  local Account = {}

  function Account:new ()
    local object = {}
    self.__index = self
    setmetatable(object, self)
    balance[object] = 0
    return object
  end

  function Account:deposit (v)
    balance[self] = balance[self] + v
  end

  function Account:withdraw (v)
    if amount > self.balance then error("insufficient funds") end
    balance[self] = balance[self] - v
  end

  function Account:balance ()
    return balance[self]
  end

  return Account
#+end_src

*** Inheritance

#+begin_src lua
  Account = { balance = 0 }

  function Account:new (object)
    object = object or {}
    self.__index = self
    setmetatable(object, self)
  end

  function Account:deposit (v)
    self.balance = self.balance + v
  end

  function Account:withdraw (v)
    if v > self.balance then error("insufficient funds") end
    self.balance = self.balance - v
  end

  SpecialAccount = Account:new()

  function SpecialAccount:withdraw (v)
    if v - self.balance >= self:getLimit() then
      error("insufficient funds")
    end
    self.balance = self.balance - v
  end

  function SpecialAccount:getLimit ()
    return self.limit or 0
  end

  account = SpecialAccount:new{ limit = 1000.00 }

  function account:getLimit ()
    return self.balance * 0.10
  end
#+end_src
